"""
Diagnostic Agent — Layer 3: Reasoning-to-Action (Step 1 of 3)
Thesis: Agentic AI for Predictive Maintenance | Danaya Diarra | March 2026

ROLE IN PIPELINE:
  Receives:  AlertJSON (Interpreter Agent) + EvidenceBundle (RAG Pipeline)
  Produces:  DiagnosticReport — cited root-cause analysis, confidence score,
             ranked action recommendations, and structured handoff to Planning Agent

ARCHITECTURE:
  Implements ReAct-style reasoning (Reason → Act → Observe loop) with
  multi-step pre-planning (Pre-Act pattern, Rawat et al. 2025).

  In production: calls Anthropic Claude API with the constructed prompt.
  Offline mode: uses deterministic rule-based reasoning engine that mirrors
  the LLM reasoning structure — same output schema, same citation format.
  Switch: set USE_LLM=True and provide ANTHROPIC_API_KEY in environment.

OUTPUT CONTRACT (DiagnosticReport):
  - root_cause_primary:     most likely fault mechanism with evidence chain
  - root_cause_alternatives: ranked alternatives with supporting evidence
  - confidence_score:       0.0–1.0 calibrated to evidence coverage + urgency
  - action_recommendations: ranked list with risk tier and SLA
  - citations_used:         all [DOC-ID] references in reasoning
  - hallucination_check:    fraction of claims traceable to retrieved evidence
  - reasoning_trace:        full step-by-step reasoning for audit log
  - handoff_to_planner:     structured dict consumed by Planning Agent
"""

import os, json, time, re
from dataclasses import dataclass, asdict, field
from typing import List, Optional, Dict

USE_LLM     = os.environ.get("USE_LLM", "false").lower() == "true"
API_KEY     = os.environ.get("ANTHROPIC_API_KEY", "")
MODEL_ID    = "claude-sonnet-4-6"

RESULTS_DIR = "results/diagnostic"
os.makedirs(RESULTS_DIR, exist_ok=True)

# ── Data structures ────────────────────────────────────────────────────────

@dataclass
class ActionRecommendation:
    rank:            int
    action:          str
    rationale:       str
    risk_tier:       int          # 1=auto, 2=timeout, 3=human required
    sla_hours:       int
    tool_call:       str          # which tool to invoke
    tool_params:     dict
    citations:       List[str]

@dataclass
class DiagnosticReport:
    # Identity
    report_id:              str
    station_id:             str
    alert_id:               str
    urgency:                str
    timestamp:              str

    # Core diagnosis
    root_cause_primary:     str
    root_cause_evidence:    List[str]    # citation refs supporting primary
    root_cause_alternatives: List[dict]  # [{hypothesis, confidence, citations}]
    diagnostic_confidence:  float        # 0.0–1.0

    # Actions
    action_recommendations: List[dict]   # ActionRecommendation dicts

    # Quality metrics
    citations_used:         List[str]
    hallucination_rate:     float        # 0.0 = fully grounded
    grounding_rate:         float        # 1.0 = fully grounded
    evidence_coverage:      float        # from EvidenceBundle.coverage_score

    # Reasoning audit trail
    reasoning_trace:        List[str]    # step-by-step reasoning steps
    reasoning_engine:       str          # "llm" | "rule_based"

    # Precision diagnosis fields (new — required for goal: what is fault + what to do)
    fault_component:        str = ""    # exact failing component
    fault_mechanism:        str = ""    # physical degradation mechanism
    alarm_code:             str = ""    # alarm code this will trigger
    repair_procedure:       list = None # numbered step-by-step repair steps
    parts_required:         list = None # exact parts list
    skill_level:            str = ""    # required skill level
    time_estimate_h:        float = 0.0 # total time hours (travel+repair+test)

    # Handoff to Planning Agent
    handoff_to_planner:     dict = None


# ── Prompt Builder ─────────────────────────────────────────────────────────

class PromptBuilder:
    """Constructs the structured LLM prompt from AlertJSON + EvidenceBundle."""

    SYSTEM_PROMPT = """You are a senior telecom field engineer and AI diagnostic agent
specialised in base station predictive maintenance. Your task is to produce a
PRECISE, ACTIONABLE diagnostic report that answers two questions exactly:

  1. WHAT IS THE FAULT? — Name the specific failing component, the physical
     degradation mechanism, and the alarm code it will trigger.
  2. WHAT MUST BE DONE? — Provide a numbered step-by-step repair procedure,
     the exact spare parts required, the skill level needed, and the time estimate.

CONTEXT: The RUL prediction was generated by XGBoost v2 Final (15,000 trees, exp(α=3) sample weights, RMSE=12.77, R²=0.9038). Feature importances are from this model and map directly to telecom subsystems.

RULES:
1. Every factual claim MUST cite a source document in the format [DOC-ID].
   Do NOT invent information not present in the retrieved evidence.
2. Be specific: say "replace the 48V rectifier module (Huawei ETP48200)"
   NOT "check the power unit". Say "clean air filter with compressed air at
   2-bar pressure" NOT "perform maintenance".
3. Root cause MUST name the physical mechanism:
   e.g. "bearing fatigue in fan unit FAN-A causing oscillating speed drop"
   NOT "fan is degrading".
4. Repair steps MUST be numbered, each ≤15 words, executable by a field engineer.
5. Parts list: part name, part number if known from evidence, quantity.
6. Time estimate in hours (travel + repair + test).
7. Quantify confidence: high (>0.85), moderate (0.60-0.85), low (<0.60).
8. Respond with a single valid JSON object only. No markdown, no preamble.

The output will be read directly by a field engineer making a maintenance decision.
Vague language costs time and money. Be exact."""

    @staticmethod
    def build(alert: dict, bundle: dict) -> str:
        """Build the full prompt string."""
        # Serialize evidence chunks compactly
        evidence_text = ""
        for i, chunk in enumerate(bundle["chunks"], 1):
            evidence_text += (
                f"\n[{chunk['citation_ref']}] {chunk['doc_type'].upper()} — "
                f"{chunk['title']}\n{chunk['text'][:600]}...\n"
            )

        prompt = f"""PREDICTIVE MAINTENANCE DIAGNOSTIC TASK

=== ALERT (from Interpreter Agent) ===
Station ID:        {alert['station_id']}
Alert ID:          {alert['alert_id']}
Predicted RUL:     {alert['rul_cycles']} cycles
Confidence range:  {alert['confidence_low']}–{alert['confidence_high']} cycles
Urgency:           {alert['urgency']} (Governance Tier {alert['governance_tier']})
SLA:               {alert['sla_hours']} hours
Primary subsystem: {alert['primary_subsystem']}
Fault hypothesis:  {alert['fault_hypothesis']}
Situation summary: {alert['situation_summary']}

Top contributing features:
{json.dumps(alert['contributing_signals'][:3], indent=2)}

=== RETRIEVED EVIDENCE ({len(bundle['chunks'])} chunks, coverage={bundle['coverage_score']}) ===
{evidence_text}

=== TASK ===
1. Analyse the alert and evidence to identify the most probable root cause.
2. Identify 1-2 alternative hypotheses with supporting evidence.
3. Recommend 2-3 concrete maintenance actions, ranked by priority.
4. Assign a diagnostic confidence score (0.0-1.0).
5. Cite every claim with [DOC-ID] references.
6. Produce a step-by-step reasoning trace (minimum 5 steps).

REQUIRED JSON FIELDS (all mandatory):
{{
  "fault_component":        "Exact component name and model if known",
  "fault_mechanism":        "Physical degradation mechanism in one sentence",
  "alarm_code":             "Alarm code(s) this will trigger per evidence",
  "root_cause_primary":     "Full cited diagnosis with [DOC-ID] references",
  "root_cause_evidence":    ["[DOC-ID-1]", "[DOC-ID-2]"],
  "root_cause_alternatives": [{{"hypothesis":"...","confidence":0.0,"citations":["[DOC-ID]"]}}],
  "diagnostic_confidence":  0.0,
  "repair_procedure": [
    {{"step": 1, "action": "Exact step text 15 words max", "tool": "tool needed"}},
    ...
  ],
  "parts_required": [
    {{"part_name": "...", "part_number": "if known", "quantity": 1}}
  ],
  "skill_level":     "junior_technician | field_engineer | rf_specialist | bbu_specialist",
  "time_estimate_h": 0.0,
  "action_recommendations": [
    {{"rank":1,"action":"...","rationale":"[DOC-ID] ...","risk_tier":1,"sla_hours":0,
     "tool_call":"...","tool_params":{{}},"citations":["[DOC-ID]"]}}
  ],
  "citations_used":  ["[DOC-ID-1]"],
  "hallucination_rate": 0.0,
  "grounding_rate":  1.0,
  "reasoning_trace": ["Step 1: ...", "Step 2: ...", "Step 3: ...", "Step 4: ...", "Step 5: ..."]
}}"""
        return prompt


# ── LLM Engine ────────────────────────────────────────────────────────────

class LLMEngine:
    """Calls Anthropic Claude API. Used when USE_LLM=True."""

    def __init__(self, api_key: str, model: str):
        self.api_key = api_key
        self.model   = model

    def call(self, system: str, user: str) -> dict:
        try:
            import urllib.request
            payload = json.dumps({
                "model": self.model,
                "max_tokens": 2000,
                "system": system,
                "messages": [{"role": "user", "content": user}]
            }).encode()
            req = urllib.request.Request(
                "https://api.anthropic.com/v1/messages",
                data=payload,
                headers={
                    "x-api-key": self.api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json"
                })
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read())
                text = data["content"][0]["text"]
                # Strip markdown fences if present
                text = re.sub(r"^```json\s*", "", text.strip())
                text = re.sub(r"\s*```$", "", text)
                return json.loads(text)
        except Exception as e:
            print(f"  [LLM] API call failed: {e}. Falling back to rule engine.")
            return None


# ── Rule-Based Reasoning Engine (offline fallback) ────────────────────────

class RuleEngine:
    """
    Deterministic reasoning engine that mirrors the LLM output schema.
    Encodes expert telecom maintenance knowledge as structured rules.
    Produces identical output format to the LLM path for seamless swap.

    Rule structure:
      subsystem + urgency + doc_types_present → diagnosis + actions
    """

    # ── Knowledge rules per subsystem ──
    RULES = {
        "power_subsystem": {
            "primary_template": (
                "Power unit degradation is the primary root cause, "
                "characterised by voltage instability in the rectifier module "
                "and/or approaching end-of-life battery capacity. "
                "{sop_ref} prescribes immediate remote diagnosis via OMC, "
                "followed by rectifier reset attempt. "
                "{alarm_ref} confirms that PWR-001 (undervoltage) is the "
                "triggering alarm condition. "
                "{manual_ref} specifies replacement threshold at >5% voltage "
                "ripple or 7-year service life. "
                "{ticket_ref} documents a precedent incident resolved in 4h14m "
                "with generator activation as first line of response."
            ),
            "alternatives": [
                {
                    "hypothesis": "Mains grid failure (PWR-004) without hardware fault",
                    "confidence": 0.35,
                    "evidence_key": "alarm_dict"
                },
                {
                    "hypothesis": "Battery end-of-life requiring string replacement (BBU-001)",
                    "confidence": 0.25,
                    "evidence_key": "manual"
                }
            ],
            "actions_critical": [
                {
                    "action": "Execute remote rectifier reset via OMC and verify output voltage",
                    "rationale": "First-line remote remediation per {sop_ref} Step 2",
                    "risk_tier": 1, "sla_hours": 1,
                    "tool_call": "query_cmdb",
                    "tool_params": {"query_type": "alarm_status", "alarm_codes": ["PWR-001","PWR-004"]}
                },
                {
                    "action": "Dispatch field engineer with power specialisation and rectifier spare",
                    "rationale": "Remote reset SLA exceeded or unsuccessful per {sop_ref} Step 3",
                    "risk_tier": 2, "sla_hours": 4,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "critical", "skill": "power_specialist",
                                    "spares": ["rectifier_module", "BBU_fuse_set"]}
                },
                {
                    "action": "Open Critical monitoring ticket and set 30-minute review cadence",
                    "rationale": "Governance Tier 3 — audit trail required for all critical dispatches",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "critical", "subsystem": "power",
                                    "auto_escalate_minutes": 30}
                },
            ],
            "actions_warning": [
                {
                    "action": "Schedule preventive power inspection within 48h SLA",
                    "rationale": "Warning urgency — non-emergency dispatch within SLA",
                    "risk_tier": 2, "sla_hours": 48,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "warning", "skill": "power_technician",
                                    "inspection_type": "power_preventive"}
                },
                {
                    "action": "Open Warning ticket and monitor voltage trend hourly",
                    "rationale": "Trend monitoring required per {manual_ref} guidance",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "warning", "subsystem": "power",
                                    "monitoring_interval_minutes": 60}
                },
            ],
            "fault_component":  "48V DC rectifier module or battery backup unit (BBU)",
            "fault_mechanism":  "Rectifier output voltage decay below 44V threshold due to component aging or AC input instability",
            "alarm_code":       "PWR-001 (undervoltage) or PWR-004 (mains failure) per [ALM-REF]",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 4.0, "Warning": 6.0, "Monitor": 8.0},
            "repair_procedure": [
                {"step":1,"action":"Run remote OMC alarm query — confirm PWR-001 or PWR-004","tool":"OMC terminal"},
                {"step":2,"action":"Check AC mains status via remote SCADA; verify grid feed","tool":"SCADA dashboard"},
                {"step":3,"action":"Measure rectifier output voltage at PDB — expect 47.5–51.5V","tool":"Calibrated multimeter"},
                {"step":4,"action":"If voltage <44V: swap rectifier module in redundant slot","tool":"Screwdriver, ESD strap"},
                {"step":5,"action":"Perform battery capacity test: load discharge to 80%, measure runtime","tool":"Load bank"},
                {"step":6,"action":"Replace battery string if capacity <80% of rated (100Ah macro)","tool":"Lifting equipment"},
                {"step":7,"action":"Verify output voltage 47.5–51.5V for 30 min; clear alarms","tool":"Multimeter, OMC"},
            ],
            "parts_required": [
                {"part_name":"Rectifier module 48V/50A","part_number":"See MAN-PWR-001","quantity":1},
                {"part_name":"Battery string 100Ah VRLA","part_number":"See MAN-PWR-002","quantity":1},
                {"part_name":"BBU fuse set","part_number":"PWR-FUSE-KIT","quantity":1},
            ],
            "confidence_base": {
                "Critical": 0.88,
                "Warning":  0.78,
                "Monitor":  0.65
            }
        },

        "thermal_management": {
            "primary_template": (
                "Thermal management degradation is the primary root cause, "
                "with cooling fan wear as the leading mechanism. "
                "{manual_ref} specifies that fan bearing replacement is required "
                "at 40,000 operating hours, and COOL-001 triggers when fan speed "
                "drops below 2,000 RPM. "
                "{sop_ref} prescribes immediate TX power reduction to 50% on "
                "COOL-001 activation to prevent thermal runaway. "
                "{ticket_ref} documents a precedent where both fans were replaced "
                "at 38,000h after bearing failure — consistent with observed "
                "temperature trend. "
                "{alarm_ref} confirms that co-active COOL-001 and COOL-002 "
                "indicate fan failure with ambient temperature elevation."
            ),
            "alternatives": [
                {
                    "hypothesis": "Air filter blockage causing reduced airflow without fan failure",
                    "confidence": 0.30,
                    "evidence_key": "sop"
                },
                {
                    "hypothesis": "High ambient temperature exceeding design envelope",
                    "confidence": 0.20,
                    "evidence_key": "manual"
                }
            ],
            "actions_critical": [
                {
                    "action": "Reduce TX power 50% immediately via OMC command",
                    "rationale": "COOL-003 active — mandatory per {sop_ref} immediate action",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "remote_command",
                    "tool_params": {"command": "tx_power_reduction", "reduction_pct": 50}
                },
                {
                    "action": "Dispatch emergency field engineer within 4h — fan and bearing replacement",
                    "rationale": "Fan failure confirmed per {ticket_ref} pattern — 5h13m precedent",
                    "risk_tier": 3, "sla_hours": 4,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "emergency", "skill": "field_engineer",
                                    "spares": ["cooling_fan_x2", "air_filter"]}
                },
                {
                    "action": "Open Critical ticket; set thermal shutdown trigger at 75°C",
                    "rationale": "Thermal runaway prevention per {manual_ref} emergency procedure",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "critical", "subsystem": "thermal",
                                    "shutdown_trigger_celsius": 75}
                },
            ],
            "actions_warning": [
                {
                    "action": "Schedule fan inspection within 48h — check bearing temperature",
                    "rationale": "Warning pattern matches early-stage bearing wear per {manual_ref}",
                    "risk_tier": 2, "sla_hours": 48,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "warning", "skill": "field_engineer",
                                    "inspection_type": "thermal_preventive",
                                    "spares": ["cooling_fan_x2"]}
                },
                {
                    "action": "Open Warning ticket; monitor temperature trend at 15-min intervals",
                    "rationale": "Temperature logged at 15-min intervals per {manual_ref}",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "warning", "subsystem": "thermal",
                                    "monitoring_interval_minutes": 15}
                },
            ],
            "confidence_base": {"Critical": 0.91, "Warning": 0.82, "Monitor": 0.68},
            "fault_component":  "Cooling fan unit (FAN-A / FAN-B) — bearing or motor winding",
            "fault_mechanism":  "Fan bearing fatigue causing speed reduction below 2000 RPM, leading to cabinet temperature rise above 55°C threshold",
            "alarm_code":       "COOL-001 (fan speed low) or COOL-002/003 (temperature high)",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 3.0, "Warning": 5.0, "Monitor": 6.0},
            "repair_procedure": [
                {"step":1,"action":"Issue remote OMC TX power reduction to 50% immediately","tool":"OMC terminal"},
                {"step":2,"action":"Confirm COOL-001 — check fan speed reading in OMC diagnostics","tool":"OMC dashboard"},
                {"step":3,"action":"Set auto-shutdown trigger at 75°C via OMC configuration","tool":"OMC terminal"},
                {"step":4,"action":"Open cabinet top panel; listen for bearing noise on both fans","tool":"Flashlight, ear protection"},
                {"step":5,"action":"Replace failed fan: unplug 3-pin connector, remove 4xM4 bolts","tool":"Torque wrench 2.5Nm"},
                {"step":6,"action":"Clean air filter with 2-bar compressed air; replace if torn","tool":"Compressed air, filter kit"},
                {"step":7,"action":"Restore TX 100%; monitor cabinet temp 30 min confirming <40°C","tool":"OMC terminal"},
            ],
            "parts_required": [
                {"part_name": "Cooling fan assembly 48VDC", "part_number": "See MAN-THM-001", "quantity": 2},
                {"part_name": "Cabinet air filter", "part_number": "FILTER-MACRO-STD", "quantity": 1},
            ],
        },

        "rf_antenna": {
            "primary_template": (
                "RF chain degradation, specifically antenna connector corrosion, "
                "is the primary root cause. "
                "{manual_ref} identifies connector corrosion as the leading cause "
                "of VSWR degradation in outdoor deployments. "
                "{fmea_ref} assigns this failure mode the highest RPN of 175 in "
                "the RF chain. "
                "{sop_ref} provides the full connector inspection and replacement "
                "procedure including PIM testing at the -150 dBc threshold. "
                "{ticket_ref} documents a precedent with 18-day gradual VSWR "
                "increase — matching the observed degradation signature."
            ),
            "alternatives": [
                {
                    "hypothesis": "PA module output power degradation (RF-002)",
                    "confidence": 0.28,
                    "evidence_key": "alarm_dict"
                },
                {
                    "hypothesis": "Feeder cable water ingress causing dielectric loss",
                    "confidence": 0.22,
                    "evidence_key": "fmea"
                }
            ],
            "actions_warning": [
                {
                    "action": "Schedule antenna connector inspection and PIM test within SLA",
                    "rationale": "Gradual VSWR pattern confirmed — connector corrosion likely per {sop_ref}",
                    "risk_tier": 2, "sla_hours": 48,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "warning", "skill": "rf_technician",
                                    "tools": ["PIM_analyser", "torque_wrench", "IPA_spray"],
                                    "spares": ["7_16_DIN_connector_x3", "self_amalgamating_tape"]}
                },
                {
                    "action": "Open Warning ticket; pull VSWR trend last 30 days from OMC",
                    "rationale": "Trend analysis required to confirm gradual vs sudden pattern",
                    "risk_tier": 1, "sla_hours": 0,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "warning", "subsystem": "rf",
                                    "data_pull": "VSWR_trend_30d"}
                },
            ],
            "actions_critical": [
                {
                    "action": "Power down affected sector via OMC; dispatch emergency within 4h",
                    "rationale": "RF-005 threshold — PA protection required per {alarm_ref}",
                    "risk_tier": 3, "sla_hours": 4,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "emergency", "skill": "rf_technician",
                                    "tools": ["PIM_analyser", "VSWR_metre"],
                                    "spares": ["connector_kit", "RRU_PA_module"]}
                },
            ],
            "fault_component":  "Antenna feeder connector (7/16 DIN) or feeder cable",
            "fault_mechanism":  "Connector corrosion or water ingress causing impedance mismatch, VSWR elevation above 2.0, and PA output power reduction",
            "alarm_code":       "RF-001 (VSWR high) or RF-002 (output power low) per [ALM-REF]",
            "skill_level":      "rf_technician",
            "time_estimate_h":  {"Critical": 4.0, "Warning": 6.0, "Monitor": 8.0},
            "repair_procedure": [
                {"step":1,"action":"Pull 30-day VSWR trend from OMC — confirm gradual vs sudden increase","tool":"OMC analytics"},
                {"step":2,"action":"Measure output power at PA port — expect within 3dB of nominal","tool":"RF power meter"},
                {"step":3,"action":"Inspect all 7/16 DIN connectors for water ingress, corrosion, torque","tool":"Torque wrench 25Nm, flashlight"},
                {"step":4,"action":"Clean corroded connector with IPA spray; dry with compressed air","tool":"IPA spray, compressed air"},
                {"step":5,"action":"Replace connector if corrosion >20% surface area — use factory-crimp","tool":"Crimping tool, 7/16 DIN kit"},
                {"step":6,"action":"Seal all connectors and cable entry with self-amalgamating tape","tool":"Self-amalgamating tape"},
                {"step":7,"action":"Run PIM test at antenna port — pass threshold: <-150 dBc","tool":"PIM analyser"},
                {"step":8,"action":"Verify VSWR <1.5 post-repair; restore sector if degraded","tool":"VSWR metre, OMC"},
            ],
            "parts_required": [
                {"part_name":"7/16 DIN connector male straight","part_number":"7-16-DIN-M-CRIMP","quantity":3},
                {"part_name":"Self-amalgamating weatherproof tape","part_number":"SAT-20M","quantity":2},
                {"part_name":"IPA cleaning spray 500ml","part_number":"IPA-500","quantity":1},
            ],
            "confidence_base": {"Critical": 0.85, "Warning": 0.80, "Monitor": 0.62}
        },

        "backhaul_connectivity": {
            "primary_template": (
                "Backhaul connectivity degradation is the primary root cause, "
                "consistent with fibre splice loss increase or, for microwave "
                "sites, antenna alignment drift. "
                "{manual_ref} specifies that latency >10ms triggers BKH-001 and "
                "that fibre degradation manifests as optical power budget reduction. "
                "{spec_ref} defines ITU-T G.826 ESR objectives; ESR trending toward "
                "1% indicates a degraded link requiring investigation. "
                "{sop_ref} prescribes OTDR-based fault localisation for fibre paths "
                "and RSL sweep for microwave alignment verification."
            ),
            "alternatives": [
                {
                    "hypothesis": "Network congestion causing apparent latency increase",
                    "confidence": 0.22,
                    "evidence_key": "manual"
                },
                {
                    "hypothesis": "Microwave rain fade on non-fibre backhaul site",
                    "confidence": 0.18,
                    "evidence_key": "sop"
                }
            ],
            "actions_monitor": [
                {
                    "action": "Open monitoring ticket; collect latency and packet-loss trend 7 days",
                    "rationale": "Monitor urgency — trend confirmation required before dispatch",
                    "risk_tier": 1, "sla_hours": 168,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "monitor", "subsystem": "backhaul",
                                    "monitoring_days": 7, "metrics": ["latency_ms","packet_loss_pct"]}
                },
                {
                    "action": "Query CMDB for backhaul transport type and last inspection date",
                    "rationale": "Fibre vs microwave determines appropriate investigation path per {sop_ref}",
                    "risk_tier": 1, "sla_hours": 1,
                    "tool_call": "query_cmdb",
                    "tool_params": {"query_type": "backhaul_config",
                                    "fields": ["transport_type","last_inspection","fibre_budget"]}
                },
                {
                    "action": "Schedule preventive backhaul inspection within 7-day SLA",
                    "rationale": "ITU-T G.826 compliance check recommended per {spec_ref}",
                    "risk_tier": 2, "sla_hours": 168,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "low", "skill": "backhaul_technician",
                                    "tools": ["OTDR", "optical_power_metre"]}
                },
            ],
            "actions_warning": [
                {
                    "action": "Dispatch backhaul technician with OTDR within 48h",
                    "rationale": "Latency degradation confirmed; OTDR localisation required per {sop_ref}",
                    "risk_tier": 2, "sla_hours": 48,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "warning", "skill": "backhaul_technician",
                                    "tools": ["OTDR","optical_power_metre","fibre_cleaner"]}
                },
            ],
            "actions_critical": [
                {
                    "action": "Escalate to NOC shift lead — backhaul link at risk of outage",
                    "rationale": "Critical backhaul failure impacts multiple services",
                    "risk_tier": 3, "sla_hours": 4,
                    "tool_call": "escalate_to_human",
                    "tool_params": {"urgency": "critical", "context": "backhaul_failure_imminent"}
                },
            ],
            "fault_component":  "Fibre splice point or microwave antenna alignment",
            "fault_mechanism":  "Optical splice loss increase (fibre) or antenna alignment drift (microwave) causing latency >10ms and throughput reduction",
            "alarm_code":       "BKH-001 (latency high) or BKH-002 (throughput low) per [ALM-REF]",
            "skill_level":      "backhaul_technician",
            "time_estimate_h":  {"Critical": 6.0, "Warning": 8.0, "Monitor": 10.0},
            "repair_procedure": [
                {"step":1,"action":"Query CMDB: confirm backhaul type (fibre vs microwave)","tool":"CMDB terminal"},
                {"step":2,"action":"Run OTDR test from ODF to far-end — locate splice event >0.3dB loss","tool":"OTDR meter"},
                {"step":3,"action":"If fibre: re-splice at fault location using fusion splicer","tool":"Fusion splicer, fibre cleaner"},
                {"step":4,"action":"If microwave: measure RSL — compare to commissioning baseline ±3dB","tool":"RSL meter, antenna alignment tool"},
                {"step":5,"action":"Adjust microwave antenna pointing: 0.05deg increments until RSL peak","tool":"Alignment tool, torque wrench"},
                {"step":6,"action":"Verify RTT <10ms and throughput >95% of nominal via OMC","tool":"OMC statistics"},
                {"step":7,"action":"Log OTDR trace and RSL reading in CMDB for baseline update","tool":"CMDB, OTDR printout"},
            ],
            "parts_required": [
                {"part_name":"Fibre fusion splice protection sleeve","part_number":"FSP-60MM","quantity":4},
                {"part_name":"Fibre cleaning kit","part_number":"FC-CLEAN-KIT","quantity":1},
            ],
            "confidence_base": {"Critical": 0.82, "Warning": 0.74, "Monitor": 0.61}
        },

        "baseband_processing": {
            "primary_template": (
                "BBU CPU overload is the primary fault, caused by processing load exceeding "
                "the 85% threshold, consistent with alarm BBU-003. "
                "{manual_ref} specifies that sustained CPU >85% for >15 min requires "
                "modulation fallback from 256QAM to 64QAM as first-line response. "
                "{sop_ref} Step 1 confirms capacity licence check before hardware action. "
                "{alarm_ref} authorises remote reboot under co-active BBU-003 + BBU-MEM-001."
            ),
            "fault_component":  "Baseband Unit (BBU) — CPU and memory subsystem",
            "fault_mechanism":  "Processing load exceeding 85% threshold, caused by licence breach, software leak, or hardware aging",
            "alarm_code":       "BBU-003 (CPU overload) or BBU-MEM-001 (memory high) per [ALM-REF]",
            "skill_level":      "bbu_specialist",
            "time_estimate_h":  {"Critical": 3.0, "Warning": 5.0, "Monitor": 6.0},
            "repair_procedure": [
                {"step":1,"action":"Check capacity licence vs active user count via OMC","tool":"OMC licence manager"},
                {"step":2,"action":"Switch modulation 256QAM → 64QAM on all carriers — reduces load 25%","tool":"OMC parameter change"},
                {"step":3,"action":"If CPU still >85%: disable secondary carrier aggregation bands","tool":"OMC carrier management"},
                {"step":4,"action":"Review running processes — identify memory-consuming software","tool":"Remote debug log (SSH)"},
                {"step":5,"action":"If software defect confirmed: apply vendor hotfix patch","tool":"OMC software management"},
                {"step":6,"action":"If hardware aging confirmed: replace BBU memory module","tool":"ESD strap, BBU manual"},
                {"step":7,"action":"Restore 256QAM; monitor CPU for 2h — confirm <70% sustained","tool":"OMC performance counters"},
            ],
            "parts_required": [
                {"part_name":"BBU memory expansion module","part_number":"See vendor BBU manual","quantity":1},
                {"part_name":"BBU capacity licence upgrade","part_number":"SW-LIC-CAP-UPG","quantity":1},
            ],
            "alternatives": [
                {"hypothesis": "Memory leak from software defect causing gradual degradation",
                 "confidence": 0.30, "evidence_key": "sop"},
                {"hypothesis": "BBU hardware component ageing (FPGA/DRAM)",
                 "confidence": 0.20, "evidence_key": "manual"}
            ],
            "actions_monitor": [
                {"action": "Open monitoring ticket; collect CPU/memory trend 7 days",
                 "rationale": "Trend confirmation before hardware action per {sop_ref}",
                 "risk_tier": 1, "sla_hours": 168,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"baseband","monitoring_days":7}},
                {"action": "Query CMDB for BBU software version and capacity licence",
                 "rationale": "Licence breach is first exclusion per {sop_ref} Step 1",
                 "risk_tier": 1, "sla_hours": 1,
                 "tool_call": "query_cmdb",
                 "tool_params": {"query_type":"bbu_config","fields":["software_version","capacity_licence"]}},
            ],
            "actions_warning": [
                {"action": "Activate modulation fallback 256QAM → 64QAM via OMC",
                 "rationale": "Reduces processing 25-30% per {manual_ref}",
                 "risk_tier": 1, "sla_hours": 0,
                 "tool_call": "remote_command",
                 "tool_params": {"command":"modulation_fallback","target_mcs":"64QAM"}},
                {"action": "Open Warning ticket; schedule BBU capacity assessment",
                 "rationale": "Recurring CPU pressure requires capacity planning per {sop_ref}",
                 "risk_tier": 2, "sla_hours": 48,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"warning","subsystem":"baseband"}},
            ],
            "actions_critical": [
                {"action": "Remote reboot BBU — CPU overload with memory exhaustion",
                 "rationale": "BBU-003+BBU-MEM-001 co-active — reboot authorised per {alarm_ref}",
                 "risk_tier": 1, "sla_hours": 0,
                 "tool_call": "remote_command",
                 "tool_params": {"command":"bbu_reboot","maintenance_window":True}},
                {"action": "Dispatch BBU specialist for hardware upgrade if reboot fails",
                 "rationale": "Post-reboot still critical — hardware path required",
                 "risk_tier": 3, "sla_hours": 4,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"critical","skill":"bbu_specialist"}},
            ],
            "confidence_base": {"Critical": 0.84, "Warning": 0.76, "Monitor": 0.68}
        },

        "sensor_array": {
            "primary_template": (
                "Sensor drift or measurement chain fault is the primary hypothesis. "
                "Rolling-mean features show abnormal patterns inconsistent with a single "
                "subsystem fault, suggesting calibration loss or ADC degradation. "
                "Evidence from retrieved documentation supports sensor calibration "
                "verification as the primary response."
            ),
            "fault_component":  "Sensor measurement chain — transducer, signal conditioner, or ADC",
            "fault_mechanism":  "Calibration drift or ADC degradation causing systematic offset across multiple sensor channels",
            "alarm_code":       "ENV-002 (sensor anomaly) — confirm via sensor self-test",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 4.0, "Warning": 6.0, "Monitor": 8.0},
            "repair_procedure": [
                {"step":1,"action":"Run OMC sensor self-test — compare readings to fleet average","tool":"OMC diagnostics"},
                {"step":2,"action":"Compare sensor readings to reference instrument on-site","tool":"Calibrated reference meter"},
                {"step":3,"action":"If offset >5%: recalibrate using vendor calibration procedure","tool":"Calibration kit, vendor manual"},
                {"step":4,"action":"If ADC fault suspected: reseat signal conditioning board","tool":"ESD strap, screwdriver"},
                {"step":5,"action":"Replace sensor module if calibration does not restore accuracy","tool":"Sensor replacement kit"},
                {"step":6,"action":"Verify all sensor readings within ±2% of reference for 1h","tool":"OMC monitoring"},
            ],
            "parts_required": [
                {"part_name":"Sensor calibration kit","part_number":"CAL-KIT-BTS","quantity":1},
            ],
            "alternatives": [
                {"hypothesis": "Multi-subsystem wear producing correlated sensor deviation",
                 "confidence": 0.35, "evidence_key": "manual"}
            ],
            "actions_monitor": [
                {"action": "Open monitoring ticket; schedule sensor calibration verification",
                 "rationale": "Sensor drift pattern — calibration check required",
                 "risk_tier": 1, "sla_hours": 168,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"sensor"}},
            ],
            "actions_warning": [
                {"action": "Dispatch technician for sensor calibration and measurement chain inspection",
                 "rationale": "Warning-level drift requires on-site verification",
                 "risk_tier": 2, "sla_hours": 48,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"warning","skill":"field_engineer","tools":["calibration_kit","multimeter"]}},
            ],
            "actions_critical": [
                {"action": "Escalate — critical sensor failure undermines all monitoring",
                 "rationale": "Sensor failure at Critical level affects all diagnostics",
                 "risk_tier": 3, "sla_hours": 4,
                 "tool_call": "escalate_to_human",
                 "tool_params": {"urgency":"critical","context":"sensor_failure_monitoring_blind_spot"}},
            ],
            "confidence_base": {"Critical": 0.70, "Warning": 0.65, "Monitor": 0.60}
        },

        "degradation_trend": {
            "primary_template": (
                "Accelerating multi-subsystem degradation is indicated by slope features "
                "across multiple parameters — consistent with end-of-life wear convergence. "
                "Evidence supports comprehensive scheduled inspection as primary response."
            ),
            "fault_component":  "Multiple subsystems — end-of-life convergence",
            "fault_mechanism":  "Concurrent wear accumulation across power, thermal, and RF subsystems beyond rated lifecycle",
            "alarm_code":       "Multiple minor alarms across subsystems — review CMDB history",
            "skill_level":      "senior_field_engineer",
            "time_estimate_h":  {"Critical": 8.0, "Warning": 10.0, "Monitor": 12.0},
            "repair_procedure": [
                {"step":1,"action":"Query CMDB: pull 90-day alarm history for all subsystems","tool":"CMDB analytics"},
                {"step":2,"action":"Inspect power unit: measure voltage, battery capacity","tool":"Multimeter, load bank"},
                {"step":3,"action":"Inspect cooling: check fan speed, filter condition, temperature log","tool":"Thermometer, tachometer"},
                {"step":4,"action":"Inspect RF: VSWR sweep on all sectors, visual connector check","tool":"VSWR metre, torque wrench"},
                {"step":5,"action":"Compile findings; prioritise faults by RMSE zone criticality","tool":"Inspection report form"},
                {"step":6,"action":"Execute repairs in priority order per individual subsystem SOPs","tool":"Per-subsystem tool kit"},
                {"step":7,"action":"Full system health check post-repair; update lifecycle records","tool":"OMC, CMDB"},
            ],
            "parts_required": [
                {"part_name":"Full maintenance kit (subsystem-specific)","part_number":"PER-SUBSYSTEM","quantity":1},
            ],
            "alternatives": [
                {"hypothesis": "Single subsystem fault masking as multi-parameter degradation",
                 "confidence": 0.28, "evidence_key": "fmea"}
            ],
            "actions_monitor": [
                {"action": "Open monitoring ticket; schedule comprehensive multi-subsystem inspection",
                 "rationale": "Degradation convergence — broad inspection required",
                 "risk_tier": 1, "sla_hours": 168,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"multi","inspection_scope":"comprehensive"}},
            ],
            "actions_warning": [
                {"action": "Schedule full site inspection within 48h SLA",
                 "rationale": "Accelerating multi-subsystem trend — broad investigation needed",
                 "risk_tier": 2, "sla_hours": 48,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"warning","skill":"senior_field_engineer","inspection_type":"full_site_audit"}},
            ],
            "actions_critical": [
                {"action": "Emergency full-site inspection — multiple systems near failure",
                 "rationale": "Critical convergence requires senior engineer on-site",
                 "risk_tier": 3, "sla_hours": 4,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"emergency","skill":"senior_field_engineer"}},
            ],
            "confidence_base": {"Critical": 0.72, "Warning": 0.66, "Monitor": 0.58}
        },

        "operational_age": {
            "primary_template": (
                "Equipment lifecycle threshold has been reached. Degradation is consistent "
                "with end-of-life wear-out phase rather than a specific acute fault. "
                "Lifecycle replacement planning is the appropriate response."
            ),
            "fault_component":  "Full BTS system — lifecycle end",
            "fault_mechanism":  "Wear-out phase of equipment lifecycle (80-100% of rated life); multiple components approaching MTBF limits simultaneously",
            "alarm_code":       "ENV-002 (component wear indicator) — lifecycle threshold alert",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 48.0, "Warning": 168.0, "Monitor": 720.0},
            "repair_procedure": [
                {"step":1,"action":"Generate lifecycle assessment report from CMDB age data","tool":"CMDB reporting"},
                {"step":2,"action":"Identify components past 80% of rated MTBF — list for replacement","tool":"CMDB analytics"},
                {"step":3,"action":"Raise capital replacement request with cost estimate to manager","tool":"CMDB procurement module"},
                {"step":4,"action":"Schedule planned replacement during lowest-traffic maintenance window","tool":"NOC scheduling"},
                {"step":5,"action":"Execute component-by-component replacement per individual SOPs","tool":"Per-component tool kit"},
            ],
            "parts_required": [
                {"part_name":"Full site lifecycle replacement kit","part_number":"TBD-PER-AUDIT","quantity":1},
            ],
            "alternatives": [],
            "actions_monitor": [
                {"action": "Open lifecycle review ticket; initiate replacement planning",
                 "rationale": "Lifecycle threshold — replacement within 1 year recommended",
                 "risk_tier": 1, "sla_hours": 720,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"lifecycle"}},
            ],
            "actions_warning": [
                {"action": "Escalate replacement to procurement; 30-day planning window",
                 "rationale": "Warning stage — replacement within 30 days recommended",
                 "risk_tier": 2, "sla_hours": 720,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"warning","subsystem":"lifecycle","procurement_lead_days":30}},
            ],
            "actions_critical": [
                {"action": "Emergency replacement — lifecycle failure imminent",
                 "rationale": "Critical age with active degradation signals",
                 "risk_tier": 3, "sla_hours": 48,
                 "tool_call": "escalate_to_human",
                 "tool_params": {"urgency":"critical","context":"lifecycle_replacement_emergency"}},
            ],
            "confidence_base": {"Critical": 0.75, "Warning": 0.68, "Monitor": 0.62}
        },

        "health_trend": {
            "primary_template": (
                "Gradual health index decline is consistent with normal end-of-life progression. "
                "The rate of decline suggests scheduled preventive maintenance is appropriate "
                "at this lifecycle stage. No single acute fault identified."
            ),
            "fault_component":  "General BTS health — multiple subsystems declining",
            "fault_mechanism":  "Cumulative wear across monitored subsystems causing progressive health index decline",
            "alarm_code":       "ENV-002 or minor alarms across subsystems — no single primary alarm",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 6.0, "Warning": 8.0, "Monitor": 10.0},
            "repair_procedure": [
                {"step":1,"action":"Review health index trend over last 90 days in OMC","tool":"OMC analytics"},
                {"step":2,"action":"Identify subsystem with steepest health decline","tool":"OMC health dashboard"},
                {"step":3,"action":"Execute preventive maintenance per highest-priority subsystem SOP","tool":"Per-subsystem tool kit"},
                {"step":4,"action":"Update CMDB with maintenance record and new health baseline","tool":"CMDB"},
            ],
            "parts_required": [
                {"part_name":"Standard preventive maintenance kit","part_number":"PM-KIT-MACRO","quantity":1},
            ],
            "alternatives": [],
            "actions_monitor": [
                {"action": "Open monitoring ticket; add to next scheduled maintenance cycle",
                 "rationale": "Health trend decline — preventive maintenance scheduling appropriate",
                 "risk_tier": 1, "sla_hours": 168,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"general"}},
            ],
            "actions_warning": [
                {"action": "Schedule preventive maintenance within 7-day SLA",
                 "rationale": "Health decline rate warrants accelerated maintenance",
                 "risk_tier": 2, "sla_hours": 168,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"warning","skill":"field_engineer","inspection_type":"preventive_health_check"}},
            ],
            "actions_critical": [
                {"action": "Emergency dispatch — health index at critical failure threshold",
                 "rationale": "Critical health index decline indicates imminent multi-system failure",
                 "risk_tier": 3, "sla_hours": 4,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"emergency","skill":"senior_field_engineer"}},
            ],
            "confidence_base": {"Critical": 0.70, "Warning": 0.64, "Monitor": 0.60}
        },

        "variability_index": {
            "primary_template": (
                "Measurement instability across multiple sensor channels suggests possible "
                "sensor or ADC fault causing spurious variability. "
                "The high standard-deviation features may indicate true physical instability "
                "or measurement chain degradation."
            ),
            "fault_component":  "Sensor chain or ADC — measurement variability",
            "fault_mechanism":  "Signal noise or ADC linearity degradation causing elevated standard deviation in sensor measurements",
            "alarm_code":       "ENV-002 (measurement anomaly) — verify via sensor cross-comparison",
            "skill_level":      "field_engineer",
            "time_estimate_h":  {"Critical": 4.0, "Warning": 5.0, "Monitor": 6.0},
            "repair_procedure": [
                {"step":1,"action":"Cross-compare sensor readings with adjacent BTS fleet baseline","tool":"OMC fleet analytics"},
                {"step":2,"action":"Run OMC sensor self-test — identify channels with >10% variability","tool":"OMC diagnostics"},
                {"step":3,"action":"Physical inspection of sensor connectors — reseat all sensor boards","tool":"ESD strap, screwdriver"},
                {"step":4,"action":"Replace ADC module if variability persists after reseating","tool":"ESD strap, ADC module"},
                {"step":5,"action":"Verify all channels stable <±2% for 2h under normal load","tool":"OMC monitoring"},
            ],
            "parts_required": [
                {"part_name":"ADC replacement module","part_number":"See vendor manual","quantity":1},
            ],
            "alternatives": [
                {"hypothesis": "Genuine physical instability in the monitored subsystem",
                 "confidence": 0.40, "evidence_key": "manual"}
            ],
            "actions_monitor": [
                {"action": "Open monitoring ticket; compare variability against fleet baseline",
                 "rationale": "Fleet baseline comparison confirms sensor fault vs real variability",
                 "risk_tier": 1, "sla_hours": 168,
                 "tool_call": "open_ticket",
                 "tool_params": {"severity":"monitor","subsystem":"sensor","analysis":"fleet_baseline_comparison"}},
            ],
            "actions_warning": [
                {"action": "Schedule sensor calibration verification within 48h",
                 "rationale": "Warning-level variability requires on-site sensor inspection",
                 "risk_tier": 2, "sla_hours": 48,
                 "tool_call": "schedule_dispatch",
                 "tool_params": {"priority":"warning","skill":"field_engineer"}},
            ],
            "actions_critical": [
                {"action": "Remote sensor self-test + dispatch if fault confirmed",
                 "rationale": "Critical variability affects all monitoring reliability",
                 "risk_tier": 2, "sla_hours": 4,
                 "tool_call": "remote_command",
                 "tool_params": {"command":"sensor_self_test","report":True}},
            ],
            "confidence_base": {"Critical": 0.65, "Warning": 0.60, "Monitor": 0.55}
        },

                # Generic fallback for variability_index, degradation_trend etc.
        "default": {
            "primary_template": (
                "Sensor signal variability and degradation trend indicators "
                "suggest multi-subsystem wear convergence. "
                "The most probable mechanism is gradual component ageing "
                "across interconnected subsystems. "
                "Evidence from retrieved documentation supports scheduled "
                "preventive inspection as the primary response."
            ),
            "alternatives": [],
            "actions_monitor": [
                {
                    "action": "Open monitoring ticket and schedule broad preventive inspection",
                    "rationale": "Multi-subsystem degradation signal — inspection to confirm subsystem",
                    "risk_tier": 1, "sla_hours": 168,
                    "tool_call": "open_ticket",
                    "tool_params": {"severity": "monitor", "subsystem": "general"}
                },
            ],
            "actions_warning": [
                {
                    "action": "Dispatch field engineer for comprehensive station health check",
                    "rationale": "Warning urgency with multi-signal degradation",
                    "risk_tier": 2, "sla_hours": 48,
                    "tool_call": "schedule_dispatch",
                    "tool_params": {"priority": "warning", "skill": "field_engineer",
                                    "inspection_type": "full_health_check"}
                },
            ],
            "actions_critical": [
                {
                    "action": "Escalate to human — multi-subsystem critical alert requires NOC review",
                    "rationale": "Multi-signal critical — human judgement required",
                    "risk_tier": 3, "sla_hours": 4,
                    "tool_call": "escalate_to_human",
                    "tool_params": {"urgency": "critical", "context": "multi_subsystem_critical"}
                },
            ],
            "confidence_base": {"Critical": 0.70, "Warning": 0.60, "Monitor": 0.50}
        }
    }

    def diagnose(self, alert: dict, bundle: dict) -> dict:
        """
        Apply rules to produce DiagnosticReport fields.
        References chunk citation_refs from the evidence bundle.
        """
        subsystem = alert["primary_subsystem"]
        urgency   = alert["urgency"]
        rule      = self.RULES.get(subsystem, self.RULES["default"])

        # Build citation reference map from bundle
        cit_by_type = {}
        for chunk in bundle["chunks"]:
            dt = chunk["doc_type"]
            if dt not in cit_by_type:
                cit_by_type[dt] = chunk["citation_ref"]

        def ref(key):
            mapping = {
                "sop_ref":    cit_by_type.get("sop",        "[SOP-REF]"),
                "alarm_ref":  cit_by_type.get("alarm_dict", "[ALM-REF]"),
                "manual_ref": cit_by_type.get("manual",     "[MAN-REF]"),
                "ticket_ref": cit_by_type.get("ticket",     "[TKT-REF]"),
                "spec_ref":   cit_by_type.get("spec",       "[SPEC-REF]"),
                "fmea_ref":   cit_by_type.get("fmea",       "[FMEA-REF]"),
                "tree_ref":   cit_by_type.get("tree",       "[TREE-REF]"),
            }
            return mapping.get(key, f"[{key.upper()}]")

        # Build primary diagnosis text with citations
        primary = rule["primary_template"].format(
            sop_ref    = ref("sop_ref"),
            alarm_ref  = ref("alarm_ref"),
            manual_ref = ref("manual_ref"),
            ticket_ref = ref("ticket_ref"),
            spec_ref   = ref("spec_ref"),
            fmea_ref   = ref("fmea_ref"),
            tree_ref   = ref("tree_ref"),
        )

        # Extract all citation refs from primary text
        citations_in_primary = re.findall(r"\[[A-Z0-9\-]+\]", primary)
        all_bundle_citations  = [c["citation_ref"] for c in bundle["chunks"]]
        citations_used        = list(set(citations_in_primary) &
                                     set(all_bundle_citations))

        # Grounding: only count citations that resolved to real doc refs
        # (unresolved placeholders format to [KEY-REF] — exclude these)
        real_cites = [c for c in citations_in_primary if not c.endswith("-REF]")]
        grounding = (len([c for c in real_cites if c in all_bundle_citations]) /
                     max(1, len(real_cites))) if real_cites else 1.0

        # Build alternatives with citations
        alternatives = []
        for alt in rule.get("alternatives", []):
            cit = cit_by_type.get(alt["evidence_key"], "[REF]")
            alternatives.append({
                "hypothesis":  alt["hypothesis"],
                "confidence":  alt["confidence"],
                "citations":   [cit],
                "rationale":   f"Supported by {cit} — alternative mechanism not excluded by current data"
            })

        # Select actions by urgency
        action_key = f"actions_{urgency.lower()}"
        raw_actions = rule.get(action_key,
                    rule.get("actions_warning",
                    rule.get("actions_monitor",
                    rule.get("actions_critical", []))))

        actions = []
        for rank, a in enumerate(raw_actions, 1):
            rationale = a["rationale"].format(
                sop_ref=ref("sop_ref"), alarm_ref=ref("alarm_ref"),
                manual_ref=ref("manual_ref"), ticket_ref=ref("ticket_ref"),
                spec_ref=ref("spec_ref"), fmea_ref=ref("fmea_ref"))
            cits_in_rationale = re.findall(r"\[[A-Z0-9\-]+\]", rationale)
            actions.append(asdict(ActionRecommendation(
                rank=rank,
                action=a["action"],
                rationale=rationale,
                risk_tier=a["risk_tier"],
                sla_hours=a["sla_hours"],
                tool_call=a["tool_call"],
                tool_params=a["tool_params"],
                citations=cits_in_rationale,
            )))

        # Confidence: base × coverage × grounding adjustment
        conf_base   = rule["confidence_base"].get(urgency, 0.70)
        conf_final  = round(conf_base * bundle["coverage_score"] * (0.7 + 0.3*grounding), 3)

        # Reasoning trace
        trace = [
            f"Step 1 [Observe]: Received alert for {alert['station_id']} — "
            f"RUL {alert['rul_cycles']} cycles, urgency {urgency}, "
            f"primary subsystem {subsystem}.",

            f"Step 2 [Query RAG]: Retrieved {len(bundle['chunks'])} evidence chunks "
            f"(coverage={bundle['coverage_score']}) in {bundle['retrieval_latency_ms']}ms. "
            f"Top chunk: {bundle['chunks'][0]['title'] if bundle['chunks'] else 'none'}.",

            f"Step 3 [Hypothesis formation]: Applied {subsystem} rule set. "
            f"Primary hypothesis confirmed by {len(citations_used)} matching citations: "
            f"{', '.join(citations_used)}.",

            f"Step 4 [Alternative evaluation]: {len(alternatives)} alternative "
            f"hypotheses considered. Primary confidence {conf_final:.3f} after "
            f"coverage×grounding adjustment (base {conf_base}).",

            f"Step 5 [Action selection]: Selected {len(actions)} actions for "
            f"{urgency} urgency. Highest risk action: Tier "
            f"{max((a['risk_tier'] for a in actions), default=1)}. "
            f"First tool call: {actions[0]['tool_call'] if actions else 'none'}.",

            f"Step 6 [Grounding check]: Grounding rate {grounding:.3f} — "
            f"{'PASS (all claims cited)' if grounding >= 0.8 else 'PARTIAL (some claims need verification)'}. "
            f"Hallucination rate: {round(1-grounding, 3)}.",

            f"Step 7 [Handoff]: Report ready for Planning Agent. "
            f"Primary action: '{actions[0]['action'][:60]}...' " if actions else
            f"Step 7 [Handoff]: No actions generated — escalate.",
        ]

        # Build repair procedure + parts from rule set
        repair_info = rule.get("repair_procedure", [])
        parts_info  = rule.get("parts_required", [])
        skill_info  = rule.get("skill_level", "field_engineer")
        time_info   = rule.get("time_estimate_h", {}).get(urgency, 4.0)
        fault_comp  = rule.get("fault_component", subsystem.replace("_"," ").title())
        fault_mech  = rule.get("fault_mechanism", f"{subsystem} degradation detected")
        alarm_info  = rule.get("alarm_code", "")

        return {
            "fault_component":         fault_comp,
            "fault_mechanism":         fault_mech,
            "alarm_code":              alarm_info,
            "repair_procedure":        repair_info,
            "parts_required":          parts_info,
            "skill_level":             skill_info,
            "time_estimate_h":         float(time_info),
            "root_cause_primary":      primary,
            "root_cause_evidence":     citations_used,
            "root_cause_alternatives": alternatives,
            "diagnostic_confidence":   conf_final,
            "action_recommendations":  actions,
            "citations_used":          citations_used,
            "hallucination_rate":      round(1 - grounding, 3),
            "grounding_rate":          round(grounding, 3),
            "reasoning_trace":         trace,
        }


# ── Diagnostic Agent Orchestrator ─────────────────────────────────────────

class DiagnosticAgent:
    """
    Orchestrates: AlertJSON + EvidenceBundle → DiagnosticReport.
    Uses LLM engine if USE_LLM=True and API key present; else rule engine.
    Output schema is identical in both cases.
    """

    def __init__(self):
        self.rule_engine = RuleEngine()
        self.llm_engine  = LLMEngine(API_KEY, MODEL_ID) if USE_LLM else None
        self.engine_used = "llm" if (USE_LLM and API_KEY) else "rule_based"
        print(f"  [DiagnosticAgent] Engine: {self.engine_used}")

    def diagnose(self, alert: dict, bundle: dict) -> DiagnosticReport:
        t0 = time.time()

        if self.engine_used == "llm" and self.llm_engine:
            prompt  = PromptBuilder.build(alert, bundle)
            result  = self.llm_engine.call(PromptBuilder.SYSTEM_PROMPT, prompt)
            if result is None:
                result = self.rule_engine.diagnose(alert, bundle)
                engine = "rule_based_fallback"
            else:
                engine = "llm"
        else:
            result = self.rule_engine.diagnose(alert, bundle)
            engine = "rule_based"

        # Handoff packet for Planning Agent
        actions = result.get("action_recommendations", [])
        handoff = {
            "station_id":        alert["station_id"],
            "urgency":           alert["urgency"],
            "governance_tier":   alert["governance_tier"],
            "sla_hours":         alert["sla_hours"],
            "primary_action":    actions[0] if actions else None,
            "all_actions":       actions,
            "confidence":        result.get("diagnostic_confidence", 0.0),
            "citations":         result.get("citations_used", []),
            "auto_execute":      alert.get("auto_execute", False),
            "escalation_path":   alert.get("escalation_path", ""),
            # Precision diagnosis — what is the fault and exactly what to do
            "fault_component":   result.get("fault_component", ""),
            "fault_mechanism":   result.get("fault_mechanism", ""),
            "alarm_code":        result.get("alarm_code", ""),
            "repair_procedure":  result.get("repair_procedure", []),
            "parts_required":    result.get("parts_required", []),
            "skill_level":       result.get("skill_level", "field_engineer"),
            "time_estimate_h":   result.get("time_estimate_h", 4.0),
        }

        import pandas as pd
        report = DiagnosticReport(
            report_id              = f"DIAG_{alert['station_id']}_{int(time.time())}",
            station_id             = alert["station_id"],
            alert_id               = alert["alert_id"],
            urgency                = alert["urgency"],
            timestamp              = pd.Timestamp.now().isoformat(),
            fault_component        = result.get("fault_component", ""),
            fault_mechanism        = result.get("fault_mechanism", ""),
            alarm_code             = result.get("alarm_code", ""),
            repair_procedure       = result.get("repair_procedure", []),
            parts_required         = result.get("parts_required", []),
            skill_level            = result.get("skill_level", "field_engineer"),
            time_estimate_h        = float(result.get("time_estimate_h", 4.0)),
            root_cause_primary     = result["root_cause_primary"],
            root_cause_evidence    = result["root_cause_evidence"],
            root_cause_alternatives= result["root_cause_alternatives"],
            diagnostic_confidence  = result["diagnostic_confidence"],
            action_recommendations = result["action_recommendations"],
            citations_used         = result["citations_used"],
            hallucination_rate     = result["hallucination_rate"],
            grounding_rate         = result["grounding_rate"],
            evidence_coverage      = bundle["coverage_score"],
            reasoning_trace        = result["reasoning_trace"],
            reasoning_engine       = engine,
            handoff_to_planner     = handoff,
        )
        elapsed = (time.time() - t0) * 1000
        print(f"  [DiagnosticAgent] {alert['station_id']} → "
              f"confidence={report.diagnostic_confidence:.3f}  "
              f"grounding={report.grounding_rate:.3f}  "
              f"engine={engine}  {elapsed:.1f}ms")
        return report

    def diagnose_batch(self, alerts, bundles) -> list:
        return [self.diagnose(a, b) for a,b in zip(alerts, bundles)]


# ── Demo run ──────────────────────────────────────────────────────────────

def run_demo():
    print("=" * 68)
    print("DIAGNOSTIC AGENT — DEMO RUN")
    print("=" * 68)

    # Load evidence bundles produced by RAG pipeline
    bundle_path = "results/rag/evidence_bundles_demo.json"
    if not os.path.exists(bundle_path):
        print("  Evidence bundles not found. Run rag_pipeline.py first.")
        return

    with open(bundle_path) as f:
        bundles = json.load(f)

    # Simulated alerts from Interpreter Agent (matching bundle demo)
    alerts = [
        {
            "alert_id": "ALERT_FD002_47_demo", "station_id": "FD002_47",
            "urgency": "Critical", "governance_tier": 3,
            "rul_cycles": 14.7, "confidence_low": 11.7, "confidence_high": 17.7,
            "primary_subsystem": "power_subsystem",
            "fault_hypothesis": "Power unit degradation — voltage instability or rectifier wear",
            "situation_summary": "Station FD002_47 predicted to fail in 14.7 cycles. Power subsystem.",
            "contributing_signals": [
                {"feature_name":"total_power_slope_20","importance":0.0744,"subsystem":"power_subsystem","rank":1},
                {"feature_name":"voltage_rolling_mean","importance":0.0589,"subsystem":"power_subsystem","rank":2},
            ],
            "sla_hours": 4, "auto_execute": False,
            "escalation_path": "NOC_shift_lead → field_operations_manager",
        },
        {
            "alert_id": "ALERT_FD001_23_demo", "station_id": "FD001_23",
            "urgency": "Warning", "governance_tier": 2,
            "rul_cycles": 38.2, "confidence_low": 32.5, "confidence_high": 43.9,
            "primary_subsystem": "thermal_management",
            "fault_hypothesis": "Thermal runaway risk — cooling fan wear or blocked ventilation",
            "situation_summary": "Station FD001_23 predicted to fail in 38.2 cycles. Thermal management.",
            "contributing_signals": [
                {"feature_name":"temp_sensor_slope","importance":0.0512,"subsystem":"thermal_management","rank":1},
            ],
            "sla_hours": 48, "auto_execute": True,
            "escalation_path": "maintenance_engineer",
        },
        {
            "alert_id": "ALERT_FD004_112_demo", "station_id": "FD004_112",
            "urgency": "Monitor", "governance_tier": 1,
            "rul_cycles": 87.5, "confidence_low": 74.4, "confidence_high": 100.6,
            "primary_subsystem": "backhaul_connectivity",
            "fault_hypothesis": "Backhaul link degradation — fibre splice or microwave alignment",
            "situation_summary": "Station FD004_112 predicted in 87.5 cycles. Backhaul.",
            "contributing_signals": [
                {"feature_name":"latency_slope","importance":0.0340,"subsystem":"backhaul_connectivity","rank":1},
            ],
            "sla_hours": 168, "auto_execute": True,
            "escalation_path": "scheduled_maintenance_queue",
        },
    ]

    agent   = DiagnosticAgent()
    reports = agent.diagnose_batch(alerts, bundles)

    for report in reports:
        print(f"\n{'─'*62}")
        print(f"  REPORT:     {report.report_id}")
        print(f"  Station:    {report.station_id}  |  Urgency: {report.urgency}")
        print(f"  Confidence: {report.diagnostic_confidence:.3f}  "
              f"|  Grounding: {report.grounding_rate:.3f}  "
              f"|  Hallucination: {report.hallucination_rate:.3f}")
        print(f"  Engine:     {report.reasoning_engine}")
        print(f"\n  PRIMARY ROOT CAUSE:")
        for line in report.root_cause_primary[:400].split(". "):
            if line.strip(): print(f"    {line.strip()}.")
        print(f"\n  Evidence refs: {report.root_cause_evidence}")
        print(f"\n  ALTERNATIVES:")
        for alt in report.root_cause_alternatives:
            print(f"    [{alt['confidence']:.2f}] {alt['hypothesis']}")
            print(f"           → {alt['citations']}")
        print(f"\n  ACTION RECOMMENDATIONS:")
        for act in report.action_recommendations:
            tier_label = {1:"AUTO",2:"TIMEOUT",3:"HUMAN ✓"}.get(act['risk_tier'],'?')
            print(f"    [{act['rank']}] Tier{act['risk_tier']}({tier_label}) "
                  f"SLA={act['sla_hours']}h  tool={act['tool_call']}")
            print(f"        {act['action'][:70]}")
        print(f"\n  REASONING TRACE (abridged):")
        for step in report.reasoning_trace[:4]:
            print(f"    {step[:80]}")
        print(f"\n  HANDOFF → Planning Agent:")
        h = report.handoff_to_planner
        print(f"    primary_action: {h['primary_action']['tool_call'] if h['primary_action'] else 'none'}")
        print(f"    confidence:     {h['confidence']}")
        print(f"    auto_execute:   {h['auto_execute']}")
        print(f"    citations:      {h['citations']}")

    # Summary quality table
    print(f"\n{'─'*62}")
    print(f"  {'Station':<15} {'Urgency':<10} {'Conf':>6} {'Ground':>7} "
          f"{'Halluc':>7} {'Actions':>8} {'Engine'}")
    print(f"  {'─'*62}")
    for r in reports:
        print(f"  {r.station_id:<15} {r.urgency:<10} "
              f"{r.diagnostic_confidence:>6.3f} "
              f"{r.grounding_rate:>7.3f} "
              f"{r.hallucination_rate:>7.3f} "
              f"{len(r.action_recommendations):>8} "
              f"  {r.reasoning_engine}")

    # Save reports
    out_path = os.path.join(RESULTS_DIR, "diagnostic_reports_demo.json")
    with open(out_path, "w") as f:
        json.dump([asdict(r) for r in reports], f, indent=2)
    print(f"\n  Saved → {out_path}")
    print("=" * 68)
    print("DIAGNOSTIC AGENT DEMO COMPLETE")
    print("=" * 68)
    return reports

if __name__ == "__main__":
    run_demo()
