"""
rag_document_ingestor.py — Real Document Ingestion for FluxAgent RAG Corpus
=============================================================================
Thesis: Agentic AI for Predictive Maintenance | Danaya Diarra | GSOM SPBU | 2026

PURPOSE
-------
Ingests REAL maintenance documents into the RAG corpus, replacing the synthetic
knowledge base generated by rag_corpus_builder.py with actual vendor manuals,
operator SOPs, alarm guides, maintenance tickets, and field reports.

This is the production path for real deployment:

  REAL DOCUMENTS → rag_document_ingestor.py → data/rag_corpus/corpus.json
                                             → data/rag_index/ (TF-IDF + SVD)
                                             → streamlit_pdm.py (DiagnosticAgent)

SUPPORTED INPUT FORMATS
-----------------------
  • PDF         — vendor manuals, 3GPP specs, ITU-T recommendations
  • Word (.docx) — internal SOPs, maintenance procedures, field reports
  • HTML        — scraped vendor knowledge bases, online documentation
  • CSV / JSON  — historical ticket exports from OSS/BSS (Nokia NetAct, Ericsson OSS)
  • Plain text  — alarm dictionaries, threshold tables, engineering notes
  • Excel (.xlsx) — FMEA tables, KPI threshold sheets, spare parts catalogs

CHUNKING STRATEGY
-----------------
  • Target chunk size: 400–600 tokens (~350–500 words)
  • Overlap: 80 tokens (preserves context at boundaries)
  • Semantic splitting: respects paragraph/section boundaries (never mid-sentence)
  • Metadata tagging: auto-detect doc_type, subsystem, alarm codes from content

USAGE
-----
  # Ingest a single PDF manual
  python rag_document_ingestor.py --file docs/ericsson_rbs6601_maintenance.pdf

  # Ingest all documents in a folder
  python rag_document_ingestor.py --dir docs/vendor_manuals/

  # Ingest from a ticket export CSV (Nokia NetAct, Ericsson OSS)
  python rag_document_ingestor.py --tickets exports/maintenance_tickets_2024.csv

  # Merge with synthetic corpus (add real docs without losing baseline)
  python rag_document_ingestor.py --dir docs/ --merge

  # Full rebuild: clear synthetic corpus, ingest all real docs
  python rag_document_ingestor.py --dir docs/ --rebuild

  # Preview what would be ingested (dry run)
  python rag_document_ingestor.py --dir docs/ --dry-run

INTEGRATION WITH FluxAgent
--------------------------
After ingestion, the RAG index is automatically rebuilt and the DiagnosticAgent
will use real documents on the next query — no restart needed.

    from rag_document_ingestor import DocumentIngestor
    ingestor = DocumentIngestor()
    ingestor.ingest_file("path/to/manual.pdf")
    ingestor.rebuild_index()  # updates data/rag_index/ in place
"""

import os, re, json, hashlib, argparse, logging
from pathlib import Path
from dataclasses import dataclass, asdict, field
from typing import List, Optional
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("rag_ingestor")

# ── Paths ─────────────────────────────────────────────────────────────────────
CORPUS_DIR = Path("data/rag_corpus")
INDEX_DIR  = Path("data/rag_index")
CORPUS_DIR.mkdir(parents=True, exist_ok=True)

# ── Subsystem keyword detector ────────────────────────────────────────────────
SUBSYSTEM_KEYWORDS = {
    "power_subsystem":       ["rectifier","voltage","battery","pwr-","mains","dc bus","mcb","BBU-00"],
    "thermal_management":    ["cooling","fan","temperature","COOL-","thermal","heat exchanger","HVAC"],
    "rf_antenna":            ["vswr","antenna","RF-","feeder","PIM","connector","PA module","LNA"],
    "backhaul_connectivity": ["backhaul","latency","fibre","microwave","BKH-","OTDR","packet loss"],
    "baseband_processing":   ["BBU","baseband","CPU","BB-","software","upgrade","memory","FPGA"],
}
DOCTYPE_KEYWORDS = {
    "sop":        ["procedure","step","SOP","instruction","how to","process"],
    "manual":     ["specification","manual","datasheet","technical note","nominal","threshold"],
    "alarm_dict": ["alarm","alert","severity","probable cause","action","clear","code"],
    "ticket":     ["incident","INC-","resolution","root cause","work performed","closed"],
    "spec":       ["3GPP","ITU-T","ETSI","standard","recommendation","TS ","TR "],
    "fmea":       ["FMEA","failure mode","RPN","occurrence","severity","detection"],
    "tree":       ["decision","flowchart","triage","Q1","Q2","YES","NO","→"],
}

def detect_subsystem(text: str) -> str:
    text_lo = text.lower()
    scores = {sub: sum(1 for kw in kws if kw.lower() in text_lo)
              for sub, kws in SUBSYSTEM_KEYWORDS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "general"

def detect_doctype(text: str, filename: str = "") -> str:
    combined = (text + " " + filename).lower()
    scores = {dt: sum(1 for kw in kws if kw.lower() in combined)
              for dt, kws in DOCTYPE_KEYWORDS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "manual"

def make_chunk_id(text: str) -> str:
    return hashlib.md5(text.encode()).hexdigest()[:12]

# ── Chunk dataclass (matches rag_corpus_builder.py schema) ───────────────────
@dataclass
class Chunk:
    chunk_id:         str
    doc_id:           str
    doc_type:         str
    equipment_family: str
    subsystem:        str
    alarm_category:   Optional[str]
    software_release: Optional[str]
    title:            str
    text:             str
    keywords:         List[str]
    source_file:      str = ""
    ingested_at:      str = ""

# ── Text extractors ───────────────────────────────────────────────────────────
def extract_pdf(path: Path) -> str:
    """Extract text from PDF using pdfminer (preferred) or PyMuPDF fallback."""
    try:
        from pdfminer.high_level import extract_text
        return extract_text(str(path))
    except ImportError:
        pass
    try:
        import fitz  # PyMuPDF
        doc = fitz.open(str(path))
        return "\n".join(page.get_text() for page in doc)
    except ImportError:
        pass
    log.warning(f"No PDF library available. Install: pip install pdfminer.six OR pymupdf")
    return f"[PDF extraction unavailable — install pdfminer.six] File: {path.name}"

def extract_docx(path: Path) -> str:
    """Extract text from Word document."""
    try:
        import docx as python_docx
        doc = python_docx.Document(str(path))
        return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
    except ImportError:
        log.warning("python-docx not available. Install: pip install python-docx")
        return f"[DOCX extraction unavailable] File: {path.name}"

def extract_html(path: Path) -> str:
    """Strip HTML tags and extract plain text."""
    try:
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(path.read_text(errors="replace"), "html.parser")
        for tag in soup(["script","style","nav","footer","header"]): tag.decompose()
        return soup.get_text(separator="\n")
    except ImportError:
        # Simple regex fallback
        text = path.read_text(errors="replace")
        return re.sub(r"<[^>]+>", " ", text)

def extract_excel(path: Path) -> str:
    """Convert Excel sheet to text."""
    try:
        import openpyxl
        wb = openpyxl.load_workbook(str(path), read_only=True, data_only=True)
        lines = []
        for ws in wb.worksheets:
            lines.append(f"Sheet: {ws.title}")
            for row in ws.iter_rows(values_only=True):
                row_vals = [str(v) if v is not None else "" for v in row]
                if any(v.strip() for v in row_vals):
                    lines.append(" | ".join(row_vals))
        return "\n".join(lines)
    except ImportError:
        log.warning("openpyxl not available. Install: pip install openpyxl")
        return f"[Excel extraction unavailable] File: {path.name}"

def extract_csv(path: Path) -> str:
    """Read CSV and convert to text."""
    import csv
    lines = []
    with open(path, newline="", errors="replace") as f:
        reader = csv.DictReader(f)
        for row in reader:
            lines.append("  ".join(f"{k}: {v}" for k, v in row.items() if v.strip()))
    return "\n".join(lines)

def extract_text_raw(path: Path) -> str:
    return path.read_text(errors="replace")

EXTRACTORS = {
    ".pdf":  extract_pdf,
    ".docx": extract_docx,
    ".doc":  extract_docx,
    ".html": extract_html,
    ".htm":  extract_html,
    ".xlsx": extract_excel,
    ".xls":  extract_excel,
    ".csv":  extract_csv,
    ".txt":  extract_text_raw,
    ".md":   extract_text_raw,
    ".json": extract_text_raw,
}

# ── Semantic chunker ──────────────────────────────────────────────────────────
def semantic_chunk(text: str, target_words: int = 450, overlap_words: int = 80) -> List[str]:
    """
    Split text into chunks of ~target_words, respecting paragraph boundaries.
    Adds overlap_words of context from the previous chunk.
    """
    # Split into paragraphs first
    paragraphs = [p.strip() for p in re.split(r"\n\s*\n+", text) if p.strip()]
    chunks, current, current_words = [], [], 0
    for para in paragraphs:
        para_words = len(para.split())
        if current_words + para_words > target_words and current:
            chunk_text = "\n\n".join(current)
            chunks.append(chunk_text)
            # Overlap: keep last N words from previous chunk
            overlap_paras = []
            words_kept = 0
            for p in reversed(current):
                pw = len(p.split())
                if words_kept + pw <= overlap_words:
                    overlap_paras.insert(0, p)
                    words_kept += pw
                else:
                    break
            current = overlap_paras
            current_words = sum(len(p.split()) for p in current)
        current.append(para)
        current_words += para_words
    if current:
        chunks.append("\n\n".join(current))
    return [c for c in chunks if len(c.split()) >= 20]  # drop tiny fragments

def extract_title(text: str, filename: str, chunk_idx: int) -> str:
    """Extract a meaningful title from the first line of a chunk."""
    first_line = text.strip().split("\n")[0][:120].strip()
    if len(first_line) > 15:
        return first_line
    stem = Path(filename).stem.replace("_"," ").replace("-"," ").title()
    return f"{stem} — Part {chunk_idx+1}"

def extract_alarm_category(text: str) -> Optional[str]:
    for cat in ["power","thermal","rf","backhaul","baseband"]:
        if cat in text.lower(): return cat
    return None

def extract_keywords(text: str, subsystem: str, doctype: str) -> List[str]:
    kws = [subsystem, doctype]
    # Extract alarm codes
    kws += re.findall(r"\b(?:PWR|COOL|RF|BKH|BB|BBU)-\d+\b", text)
    # Extract model numbers / version strings
    kws += re.findall(r"\bR\d{2}[A-Z]\b", text)
    # Top content words (simple frequency)
    words = re.findall(r"\b[A-Za-z]{4,}\b", text.lower())
    stop  = {"this","that","with","from","have","been","will","they","their",
              "also","when","which","than","more","some","into","over","such"}
    freq  = {}
    for w in words:
        if w not in stop: freq[w] = freq.get(w,0)+1
    top_words = sorted(freq, key=freq.get, reverse=True)[:6]
    kws += top_words
    return list(dict.fromkeys(kws))[:12]  # deduplicate, max 12

# ── Ticket CSV ingestor ───────────────────────────────────────────────────────
def ingest_ticket_csv(path: Path) -> List[Chunk]:
    """
    Parse a maintenance ticket export CSV (Nokia NetAct / Ericsson OSS format).
    Expected columns (flexible — uses best-match): 
      ticket_id, site_id, alarm_code, description, resolution, work_done, closed_at
    """
    import csv
    chunks = []
    with open(path, newline="", errors="replace") as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader):
            # Flexible column mapping
            tid  = row.get("ticket_id", row.get("INC_ID", row.get("ID", f"TKT-{i:04d}")))
            site = row.get("site_id", row.get("station_id", row.get("SITE", "UNKNOWN")))
            desc = row.get("description", row.get("alarm_description", row.get("DESC","")))
            res  = row.get("resolution", row.get("work_done", row.get("RESOLUTION","")))
            alm  = row.get("alarm_code", row.get("ALARM", ""))
            closed = row.get("closed_at", row.get("CLOSE_DATE",""))

            text = (f"Ticket ID: {tid}\nSite: {site}\nAlarm: {alm}\n"
                    f"Description: {desc}\nResolution: {res}\nClosed: {closed}")
            if len(text.split()) < 15: continue

            sub   = detect_subsystem(text)
            title = f"Maintenance Ticket {tid} — Site {site}"
            chunk = Chunk(
                chunk_id       = make_chunk_id(text),
                doc_id         = f"TKT-{tid}",
                doc_type       = "ticket",
                equipment_family = "bts_outdoor",
                subsystem      = sub,
                alarm_category = alm[:20] if alm else None,
                software_release = None,
                title          = title,
                text           = text,
                keywords       = extract_keywords(text, sub, "ticket"),
                source_file    = path.name,
                ingested_at    = datetime.now().isoformat(),
            )
            chunks.append(chunk)
    log.info(f"  Ticket CSV: ingested {len(chunks)} tickets from {path.name}")
    return chunks

# ── Main Document Ingestor ────────────────────────────────────────────────────
class DocumentIngestor:
    """
    Ingests real maintenance documents into the FluxAgent RAG corpus.

    Usage:
        ingestor = DocumentIngestor()
        ingestor.ingest_file("path/to/manual.pdf")
        ingestor.ingest_directory("docs/")
        ingestor.rebuild_index()
    """

    def __init__(self, corpus_dir: Path = CORPUS_DIR, merge: bool = True):
        self.corpus_dir = corpus_dir
        self.merge = merge
        self.corpus_path = corpus_dir / "corpus.json"
        self.chunks: List[Chunk] = []
        self._load_existing()

    def _load_existing(self):
        if self.merge and self.corpus_path.exists():
            with open(self.corpus_path) as f:
                raw = json.load(f)
            # Reconstruct Chunk objects from dicts
            self.chunks = []
            for c in raw:
                self.chunks.append(Chunk(
                    chunk_id=c["chunk_id"], doc_id=c["doc_id"],
                    doc_type=c["doc_type"], equipment_family=c.get("equipment_family","bts_outdoor"),
                    subsystem=c["subsystem"], alarm_category=c.get("alarm_category"),
                    software_release=c.get("software_release"), title=c["title"],
                    text=c["text"], keywords=c.get("keywords",[]),
                    source_file=c.get("source_file",""), ingested_at=c.get("ingested_at",""),
                ))
            log.info(f"Loaded {len(self.chunks)} existing chunks from corpus")
        else:
            self.chunks = []

    def ingest_file(self, path: str | Path, doc_id: str = None,
                    doc_type: str = None, subsystem: str = None) -> int:
        """Ingest a single file. Returns number of chunks added."""
        path = Path(path)
        if not path.exists():
            log.error(f"File not found: {path}")
            return 0

        ext = path.suffix.lower()
        extractor = EXTRACTORS.get(ext)
        if extractor is None:
            log.warning(f"Unsupported format: {ext} — skipping {path.name}")
            return 0

        # Special handling for ticket CSVs
        if ext == ".csv" and "ticket" in path.name.lower():
            new_chunks = ingest_ticket_csv(path)
            self._merge_chunks(new_chunks)
            return len(new_chunks)

        log.info(f"Extracting: {path.name}")
        try:
            text = extractor(path)
        except Exception as e:
            log.error(f"Extraction failed for {path.name}: {e}")
            return 0

        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n{3,}", "\n\n", text)

        raw_chunks = semantic_chunk(text)
        log.info(f"  → {len(raw_chunks)} chunks from {path.name}")

        _doc_id   = doc_id   or f"DOC-{path.stem[:20].upper()}"
        _doc_type = doc_type or detect_doctype(text, path.name)
        _subsystem= subsystem or detect_subsystem(text)

        new_chunks = []
        existing_ids = {c.chunk_id for c in self.chunks}
        for idx, chunk_text in enumerate(raw_chunks):
            cid = make_chunk_id(chunk_text)
            if cid in existing_ids:
                continue  # skip duplicate
            new_chunks.append(Chunk(
                chunk_id       = cid,
                doc_id         = _doc_id,
                doc_type       = _doc_type,
                equipment_family = "bts_outdoor",
                subsystem      = detect_subsystem(chunk_text) if not subsystem else subsystem,
                alarm_category = extract_alarm_category(chunk_text),
                software_release = None,
                title          = extract_title(chunk_text, path.name, idx),
                text           = chunk_text[:1200],
                keywords       = extract_keywords(chunk_text, _subsystem, _doc_type),
                source_file    = path.name,
                ingested_at    = datetime.now().isoformat(),
            ))

        self._merge_chunks(new_chunks)
        return len(new_chunks)

    def _merge_chunks(self, new_chunks: List[Chunk]):
        existing_ids = {c.chunk_id for c in self.chunks}
        added = [c for c in new_chunks if c.chunk_id not in existing_ids]
        self.chunks.extend(added)

    def ingest_directory(self, directory: str | Path,
                         recursive: bool = True) -> int:
        """Ingest all supported documents in a directory."""
        directory = Path(directory)
        pattern   = "**/*" if recursive else "*"
        total = 0
        for path in sorted(directory.glob(pattern)):
            if path.is_file() and path.suffix.lower() in EXTRACTORS:
                total += self.ingest_file(path)
        log.info(f"Directory ingestion complete: {total} new chunks from {directory}")
        return total

    def save(self):
        """Save updated corpus to JSON."""
        with open(self.corpus_path, "w") as f:
            json.dump([asdict(c) for c in self.chunks], f, indent=2, default=str)
        log.info(f"Corpus saved: {len(self.chunks)} chunks → {self.corpus_path}")

    def rebuild_index(self):
        """Save corpus and rebuild TF-IDF + SVD RAG index."""
        self.save()
        try:
            import sys; sys.path.insert(0, str(Path(__file__).parent))
            from rag_pipeline import RAGIndex
            index = RAGIndex()
            index.load_corpus(str(self.corpus_path))
            index.build()
            index.save(str(INDEX_DIR))
            log.info(f"RAG index rebuilt: {INDEX_DIR}/")
        except ImportError as e:
            log.warning(f"rag_pipeline not available — index not rebuilt: {e}")

    def summary(self):
        by_type = {}; by_sub = {}
        for c in self.chunks:
            by_type[c.doc_type] = by_type.get(c.doc_type, 0) + 1
            by_sub[c.subsystem] = by_sub.get(c.subsystem, 0) + 1
        print(f"\n{'='*60}")
        print(f"CORPUS SUMMARY — {len(self.chunks)} total chunks")
        print(f"{'='*60}")
        print("By document type:")
        for k,v in sorted(by_type.items()): print(f"  {k:<25} {v}")
        print("By subsystem:")
        for k,v in sorted(by_sub.items()):  print(f"  {k:<35} {v}")
        print(f"{'='*60}")

# ── CLI ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="FluxAgent RAG Document Ingestor")
    parser.add_argument("--file",     help="Ingest a single file")
    parser.add_argument("--dir",      help="Ingest all files in a directory")
    parser.add_argument("--tickets",  help="Ingest a maintenance ticket CSV export")
    parser.add_argument("--merge",    action="store_true", default=True,
                        help="Merge with existing corpus (default: True)")
    parser.add_argument("--rebuild",  action="store_true",
                        help="Clear existing corpus before ingestion")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Preview without writing")
    args = parser.parse_args()

    ingestor = DocumentIngestor(merge=(args.merge and not args.rebuild))

    n = 0
    if args.file:
        n = ingestor.ingest_file(args.file)
    if args.dir:
        n = ingestor.ingest_directory(args.dir)
    if args.tickets:
        n = ingestor.ingest_file(args.tickets)

    ingestor.summary()

    if not args.dry_run:
        ingestor.save()
        ingestor.rebuild_index()
        print(f"\n✓ {n} new chunks ingested and index rebuilt.")
    else:
        print(f"\n[DRY RUN] Would add {n} chunks. No files written.")
