"""
Centralized station configuration for the Agentic PdM system.
This file contains all station metadata to avoid duplication across the codebase.

25 BTS stations: Focus on Mali (12 stations) and Senegal (11 stations), with 2 in neighboring countries.
"""

# Comprehensive station data with all metadata - 25 STATIONS
STATIONS = [
    dict(id="FD002_47",  urgency="Critical", sub="power_subsystem",       sla=4,
         cl=11.7, ch=17.7, conf=0.880, gr=1.0, hal=0.0, cost=800, auto_n=2, to_n=1, hum_n=0, cov=1.0,
         doc="SOP-PWR-001", subset="FD002", cycles=268,
         hyp="Power unit degradation — voltage instability or rectifier wear",
         fc="48V DC rectifier module", mech="Rectifier voltage decay below 44V threshold",
         alm="PWR-001 (undervoltage) or PWR-004 (mains failure)",
         a1="Execute remote rectifier reset via OMC",           a1t="AUTO",    a1tool="query_cmdb",
         a2="Dispatch field engineer — power specialisation",    a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=14.7, top_feat="voltage_rolling_mean", top_imp=0.0744,
         degrade=0.55, sensor_lbl="DC Voltage", sensor_nom=47.5, sensor_unit="V",  sensor_dir="low"),
    dict(id="FD003_88",  urgency="Critical", sub="thermal_management",    sla=4,
         cl=15.4, ch=20.8, conf=0.910, gr=1.0, hal=0.0, cost=800, auto_n=1, to_n=0, hum_n=2, cov=1.0,
         doc="SOP-THM-001", subset="FD003", cycles=291,
         hyp="Cooling fan bearing failure — COOL-001 imminent, thermal runaway risk",
         fc="Cooling fan FAN-A bearing assembly", mech="Bearing fatigue → fan speed < 2000 RPM",
         alm="COOL-001 (fan failure) + COOL-002 (temp >60°C)",
         a1="Reduce TX power 50% via OMC immediately",           a1t="AUTO",    a1tool="remote_command",
         a2="Emergency dispatch — fan replacement ≤4h",           a2t="HUMAN",   a2tool="schedule_dispatch",
         base_rul=18.1, top_feat="temp_sensor_slope", top_imp=0.0872,
         degrade=0.60, sensor_lbl="Cabinet Temp", sensor_nom=38.0, sensor_unit="°C", sensor_dir="high"),
    dict(id="FD001_23",  urgency="Warning",  sub="thermal_management",    sla=48,
         cl=32.5, ch=43.9, conf=0.820, gr=1.0, hal=0.0, cost=800, auto_n=1, to_n=1, hum_n=0, cov=1.0,
         doc="MAN-THM-001", subset="FD001", cycles=187,
         hyp="Cooling fan bearing wear — COOL-001 precursor pattern",
         fc="Cooling fan bearing or motor winding", mech="Gradual speed reduction toward 2000 RPM",
         alm="COOL-001 or COOL-002/003",
         a1="Schedule fan inspection within 48h SLA",             a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Open Warning ticket — 15-min temp monitoring",       a2t="AUTO",    a2tool="open_ticket",
         base_rul=38.2, top_feat="temp_sensor_slope", top_imp=0.0512,
         degrade=0.22, sensor_lbl="Fan Speed", sensor_nom=3200.0, sensor_unit="RPM",sensor_dir="low"),
    dict(id="FD004_55",  urgency="Warning",  sub="rf_antenna",            sla=48,
         cl=37.4, ch=50.6, conf=0.800, gr=1.0, hal=0.0, cost=800, auto_n=1, to_n=1, hum_n=0, cov=1.0,
         doc="MAN-RF-001", subset="FD004", cycles=210,
         hyp="RF chain degradation — antenna connector corrosion",
         fc="7/16 DIN feeder connector", mech="Corrosion causing VSWR > 2.0 and PA efficiency loss",
         alm="RF-001 (VSWR >2.0) or RF-002 (PA power low)",
         a1="Schedule connector inspection + PIM test ≤48h",      a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Open Warning ticket — pull VSWR 30-day trend",       a2t="AUTO",    a2tool="open_ticket",
         base_rul=44.0, top_feat="rssi_std_30", top_imp=0.0811,
         degrade=0.18, sensor_lbl="VSWR", sensor_nom=1.82, sensor_unit=":1", sensor_dir="high"),
    dict(id="FD004_112", urgency="Monitor",  sub="backhaul_connectivity", sla=168,
         cl=74.4, ch=100.6, conf=0.366, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=1, hum_n=0, cov=0.60,
         doc="MAN-BKH-001", subset="FD004", cycles=154,
         hyp="Backhaul link degradation — fibre splice loss or microwave alignment drift",
         fc="Fibre splice point or microwave alignment", mech="Splice loss → latency >10ms",
         alm="BKH-001 (latency high) or BKH-002 (throughput low)",
         a1="Open monitoring ticket — 7-day latency trend",       a1t="AUTO",    a1tool="open_ticket",
         a2="Query CMDB for backhaul type + last inspection",     a2t="AUTO",    a2tool="query_cmdb",
         base_rul=87.5, top_feat="latency_slope", top_imp=0.0683,
         degrade=0.07, sensor_lbl="Latency", sensor_nom=6.2, sensor_unit="ms", sensor_dir="high"),
    dict(id="FD003_71",  urgency="Monitor",  sub="rf_antenna",            sla=168,
         cl=46.8, ch=63.4, conf=0.620, gr=1.0, hal=0.0, cost=0, auto_n=1, to_n=1, hum_n=0, cov=1.0,
         doc="MAN-RF-001", subset="FD003", cycles=178,
         hyp="Antenna connector corrosion — gradual VSWR increase over 18 days",
         fc="7/16 DIN feeder connector sector Alpha", mech="Galvanic corrosion: Al body vs Cu pin",
         alm="RF-001 (VSWR) trending 0.08:1/day",
         a1="Schedule connector inspection + PIM test",            a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Open ticket — pull VSWR 30-day trend",               a2t="AUTO",    a2tool="open_ticket",
         base_rul=55.1, top_feat="rssi_std_30", top_imp=0.0814,
         degrade=0.05, sensor_lbl="RSSI", sensor_nom=-67.0, sensor_unit="dBm",sensor_dir="low"),
    dict(id="FD001_08",  urgency="Monitor",  sub="baseband_processing",   sla=168,
         cl=95.5, ch=129.3, conf=0.680, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=0, hum_n=0, cov=1.0,
         doc="MAN-BBU-002", subset="FD001", cycles=92,
         hyp="BBU CPU approaching 85% threshold — licence or software cause",
         fc="BBU CPU and memory subsystem", mech="Processing load trending toward BBU-003 threshold",
         alm="BBU-003 (CPU overload) or BBU-MEM-001",
         a1="Check capacity licence vs user count via OMC",        a1t="AUTO",    a1tool="query_cmdb",
         a2="Open monitoring — collect CPU/mem trend 7d",          a2t="AUTO",    a2tool="open_ticket",
         base_rul=112.4, top_feat="cpu_utilization_mean", top_imp=0.0771,
         degrade=0.04, sensor_lbl="CPU Util", sensor_nom=71.0, sensor_unit="%", sensor_dir="high"),
    dict(id="FD002_91",  urgency="Monitor",  sub="power_subsystem",       sla=168,
         cl=59.8, ch=80.8, conf=0.650, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=0, hum_n=0, cov=1.0,
         doc="MAN-PWR-002", subset="FD002", cycles=138,
         hyp="Battery backup unit nearing 80% capacity — end-of-life approaching",
         fc="VRLA battery string", mech="Capacity declining toward 80% of rated 100Ah",
         alm="BBU-001 (battery capacity) anticipated",
         a1="Schedule battery capacity test within 30d",           a1t="AUTO",    a1tool="open_ticket",
         a2="Plan battery string replacement if <80%",             a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=70.3, top_feat="voltage_rolling_mean", top_imp=0.0623,
         degrade=0.04, sensor_lbl="Battery Cap", sensor_nom=84.0, sensor_unit="%", sensor_dir="low"),
    dict(id="FD004_203", urgency="Monitor",  sub="backhaul_connectivity", sla=168,
         cl=80.8, ch=109.3, conf=0.610, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=1, hum_n=0, cov=0.60,
         doc="SPEC-ITU-001", subset="FD004", cycles=118,
         hyp="Backhaul latency increasing — ITU-T G.826 ESR compliance risk",
         fc="Fibre splice or microwave link — ESR toward 1%", mech="Cumulative splice → ESR near G.826 4%",
         alm="BKH-001 anticipated as ESR approaches 1%",
         a1="Track ESR against G.826 monthly threshold",           a1t="AUTO",    a1tool="open_ticket",
         a2="Schedule OTDR inspection within 7d",                  a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=95.0, top_feat="latency_slope", top_imp=0.0554,
         degrade=0.03, sensor_lbl="ESR", sensor_nom=0.8, sensor_unit="%", sensor_dir="high"),
    dict(id="FD001_77",  urgency="Monitor",  sub="baseband_processing",   sla=168,
         cl=101.2, ch=136.9, conf=0.620, gr=1.0, hal=0.0, cost=0, auto_n=1, to_n=0, hum_n=0, cov=1.0,
         doc="MAN-BBU-001", subset="FD001", cycles=76,
         hyp="Normal end-of-life health decline — routine maintenance appropriate",
         fc="BBU general health", mech="Cumulative wear approaching 80% lifecycle threshold",
         alm="No active alarms — preventive indicator only",
         a1="Add to next scheduled maintenance cycle ≤168h",       a1t="AUTO",    a1tool="open_ticket",
         a2=None, a2t=None, a2tool=None,
         base_rul=119.0, top_feat="cpu_utilization_mean", top_imp=0.0502,
         degrade=0.02, sensor_lbl="Health Idx", sensor_nom=62.0, sensor_unit="%", sensor_dir="low"),
    dict(id="FD002_14",  urgency="Critical", sub="power_subsystem",       sla=4,
         cl=8.2, ch=14.1, conf=0.920, gr=1.0, hal=0.0, cost=900, auto_n=2, to_n=1, hum_n=1, cov=1.00,
         doc="SOP-PWR-001", subset="FD002", cycles=312,
         hyp="Critical rectifier fault — DC bus voltage below 42V threshold",
         fc="48V DC rectifier module B", mech="Module B failure — Module A running at 140% rated load",
         alm="PWR-001 (undervoltage) + PWR-003 (rectifier failure)",
         a1="Isolate rectifier B and activate bypass via OMC",  a1t="AUTO",    a1tool="remote_command",
         a2="Emergency dispatch — dual rectifier replacement",   a2t="HUMAN",   a2tool="schedule_dispatch",
         base_rul=11.2, top_feat="voltage_rolling_mean", top_imp=0.0798,
         degrade=0.65, sensor_lbl="DC Voltage",   sensor_nom=42.8, sensor_unit="V",  sensor_dir="low"),
    dict(id="FD001_44",  urgency="Warning",  sub="rf_antenna",            sla=48,
         cl=28.1, ch=39.5, conf=0.780, gr=1.0, hal=0.0, cost=600, auto_n=1, to_n=2, hum_n=0, cov=1.00,
         doc="MAN-RF-001", subset="FD001", cycles=203,
         hyp="PA efficiency degradation — TX power anomaly detected on sector Alpha",
         fc="Power amplifier PA-2 stage", mech="PA efficiency falling 25% below nominal threshold",
         alm="RF-002 (PA power low) + RF-004 (efficiency alarm)",
         a1="Reduce TX power 20% via OMC to protect PA stage",  a1t="AUTO",    a1tool="remote_command",
         a2="Schedule PA module inspection within 48h",          a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=33.8, top_feat="rssi_std_30",         top_imp=0.0755,
         degrade=0.20, sensor_lbl="PA Efficiency", sensor_nom=78.5, sensor_unit="%", sensor_dir="low"),
    dict(id="FD003_55",  urgency="Warning",  sub="thermal_management",    sla=48,
         cl=22.0, ch=33.4, conf=0.840, gr=1.0, hal=0.0, cost=700, auto_n=1, to_n=1, hum_n=0, cov=1.00,
         doc="MAN-THM-001", subset="FD003", cycles=244,
         hyp="Heat exchanger fouling — reduced airflow causing thermal gradient",
         fc="Cabinet heat exchanger unit", mech="Particulate buildup reducing airflow by 35%",
         alm="COOL-002 (temp >60 C) + COOL-004 (fan deviation)",
         a1="Increase fan speed to maximum via OMC",             a1t="AUTO",    a1tool="remote_command",
         a2="Schedule heat exchanger cleaning within 48h",       a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=27.7, top_feat="temp_sensor_slope",   top_imp=0.0831,
         degrade=0.28, sensor_lbl="Inlet Temp",   sensor_nom=41.2, sensor_unit="C",  sensor_dir="high"),
    dict(id="FD004_78",  urgency="Monitor",  sub="baseband_processing",   sla=168,
         cl=61.0, ch=84.2, conf=0.700, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=0, hum_n=0, cov=1.00,
         doc="MAN-BBU-002", subset="FD004", cycles=167,
         hyp="BBU memory pressure — swap usage trending toward OOM threshold",
         fc="BBU DDR4 memory subsystem", mech="Memory leak in L2 process — swap at 68% of 16GB",
         alm="BBU-MEM-001 (swap >50%) trending toward BBU-MEM-002",
         a1="Restart non-critical L2 processes via OMC",         a1t="AUTO",    a1tool="remote_command",
         a2="Open monitoring — track swap/mem trend 7d",          a2t="AUTO",    a2tool="open_ticket",
         base_rul=72.6, top_feat="cpu_utilization_mean", top_imp=0.0688,
         degrade=0.06, sensor_lbl="Mem Swap",    sensor_nom=68.0, sensor_unit="%", sensor_dir="high"),
    dict(id="FD002_33",  urgency="Monitor",  sub="backhaul_connectivity", sla=168,
         cl=88.4, ch=122.0, conf=0.580, gr=1.0, hal=0.0, cost=0, auto_n=1, to_n=1, hum_n=0, cov=0.60,
         doc="MAN-BKH-001", subset="FD002", cycles=131,
         hyp="Microwave path anomaly — rain-fade increasing in frequency",
         fc="Microwave dish alignment — azimuth drift detected", mech="0.3 deg azimuth drift causing 3.2dB fade margin reduction",
         alm="BKH-003 (fade margin <10dB) anticipated",
         a1="Open monitoring ticket — track fade margin trend",   a1t="AUTO",    a1tool="open_ticket",
         a2="Schedule microwave alignment check within 14d",      a2t="TIMEOUT", a2tool="schedule_dispatch",
         base_rul=105.2, top_feat="latency_slope",       top_imp=0.0601,
         degrade=0.03, sensor_lbl="Fade Margin", sensor_nom=14.8, sensor_unit="dB", sensor_dir="low"),
    # Additional stations (16-25) - Mali & Senegal focus
    dict(id="ML_BKO_15",  urgency="Critical", sub="power_subsystem",       sla=4,
         cl=9.8, ch=16.2, conf=0.895, gr=1.0, hal=0.0, cost=850, auto_n=2, to_n=1, hum_n=1, cov=1.00,
         doc="SOP-PWR-001", subset="FD002", cycles=285,
         hyp="Critical DC bus voltage drop — rectifier module failure",
         fc="48V DC rectifier primary module", mech="Rectifier module critical fault",
         alm="PWR-001 (undervoltage) + PWR-005 (module fault)",
         a1="Emergency rectifier bypass activation via OMC", a1t="AUTO", a1tool="remote_command",
         a2="Critical dispatch — Bamako North zone ≤4h SLA", a2t="HUMAN", a2tool="schedule_dispatch",
         base_rul=13.0, top_feat="voltage_rolling_mean", top_imp=0.0788,
         degrade=0.62, sensor_lbl="DC Voltage", sensor_nom=43.2, sensor_unit="V", sensor_dir="low"),
    dict(id="SN_DKR_08",  urgency="Critical", sub="thermal_management",    sla=4,
         cl=12.1, ch=18.9, conf=0.905, gr=1.0, hal=0.0, cost=820, auto_n=1, to_n=0, hum_n=2, cov=1.00,
         doc="SOP-THM-001", subset="FD003", cycles=298,
         hyp="Cooling system critical failure — thermal shutdown imminent",
         fc="Cabinet cooling fan array", mech="Dual fan failure causing 72°C cabinet temp",
         alm="COOL-001 + COOL-003 (thermal shutdown risk)",
         a1="Emergency TX power reduction 60% via OMC", a1t="AUTO", a1tool="remote_command",
         a2="Critical dispatch — Dakar Central ≤4h", a2t="HUMAN", a2tool="schedule_dispatch",
         base_rul=15.5, top_feat="temp_sensor_slope", top_imp=0.0892,
         degrade=0.63, sensor_lbl="Cabinet Temp", sensor_nom=71.5, sensor_unit="°C", sensor_dir="high"),
    dict(id="ML_SKO_22",  urgency="Warning",  sub="rf_antenna",            sla=48,
         cl=25.7, ch=36.8, conf=0.795, gr=1.0, hal=0.0, cost=650, auto_n=1, to_n=2, hum_n=0, cov=1.00,
         doc="MAN-RF-001", subset="FD004", cycles=219,
         hyp="RF connector degradation — Sikasso site antenna Alpha",
         fc="7/16 DIN antenna connector", mech="Water ingress causing 2.3:1 VSWR",
         alm="RF-001 (VSWR >2.0) + RF-003 (connector)",
         a1="Schedule PIM test and connector inspection ≤48h", a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Open Warning ticket — VSWR trend analysis", a2t="AUTO", a2tool="open_ticket",
         base_rul=31.2, top_feat="rssi_std_30", top_imp=0.0765,
         degrade=0.24, sensor_lbl="VSWR", sensor_nom=2.15, sensor_unit=":1", sensor_dir="high"),
    dict(id="SN_THS_11",  urgency="Warning",  sub="power_subsystem",       sla=48,
         cl=28.4, ch=41.2, conf=0.810, gr=1.0, hal=0.0, cost=680, auto_n=2, to_n=1, hum_n=0, cov=1.00,
         doc="MAN-PWR-001", subset="FD002", cycles=235,
         hyp="Battery string capacity degradation — Thiès site backup",
         fc="VRLA battery string (48V 100Ah)", mech="Battery aging → 78% capacity remaining",
         alm="BBU-001 (battery capacity) trending critical",
         a1="Schedule battery load test within 48h", a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Plan battery replacement if <75%", a2t="AUTO", a2tool="open_ticket",
         base_rul=34.8, top_feat="voltage_rolling_mean", top_imp=0.0698,
         degrade=0.21, sensor_lbl="Battery Cap", sensor_nom=78.0, sensor_unit="%", sensor_dir="low"),
    dict(id="ML_MOP_17",  urgency="Warning",  sub="backhaul_connectivity", sla=48,
         cl=30.2, ch=44.5, conf=0.785, gr=1.0, hal=0.0, cost=600, auto_n=1, to_n=1, hum_n=0, cov=0.60,
         doc="MAN-BKH-001", subset="FD004", cycles=201,
         hyp="Microwave link degradation — Mopti backhaul path",
         fc="Microwave dish alignment", mech="Weather-induced misalignment 0.4° azimuth",
         alm="BKH-001 (latency high) + BKH-003 (fade)",
         a1="Schedule microwave alignment check ≤48h", a1t="TIMEOUT", a1tool="schedule_dispatch",
         a2="Open ticket — fade margin monitoring", a2t="AUTO", a2tool="open_ticket",
         base_rul=37.3, top_feat="latency_slope", top_imp=0.0723,
         degrade=0.19, sensor_lbl="Latency", sensor_nom=8.7, sensor_unit="ms", sensor_dir="high"),
    dict(id="SN_STL_05",  urgency="Monitor",  sub="thermal_management",    sla=168,
         cl=52.3, ch=71.8, conf=0.690, gr=1.0, hal=0.0, cost=0, auto_n=1, to_n=1, hum_n=0, cov=1.00,
         doc="MAN-THM-001", subset="FD003", cycles=165,
         hyp="Heat exchanger efficiency decline — Saint-Louis site",
         fc="Cabinet heat exchanger", mech="Filter clogging reducing airflow 22%",
         alm="COOL-002 (temp >60°C) anticipated",
         a1="Schedule filter cleaning within 7d", a1t="AUTO", a1tool="open_ticket",
         a2="Monitor temperature trend", a2t="AUTO", a2tool="open_ticket",
         base_rul=62.0, top_feat="temp_sensor_slope", top_imp=0.0612,
         degrade=0.08, sensor_lbl="Inlet Temp", sensor_nom=43.8, sensor_unit="°C", sensor_dir="high"),
    dict(id="ML_KYS_19",  urgency="Monitor",  sub="baseband_processing",   sla=168,
         cl=67.4, ch=93.1, conf=0.665, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=0, hum_n=0, cov=1.00,
         doc="MAN-BBU-002", subset="FD001", cycles=142,
         hyp="BBU CPU utilization trending up — Kayes site load increase",
         fc="BBU CPU subsystem", mech="User capacity approaching licence limit",
         alm="BBU-003 (CPU high) anticipated if >85%",
         a1="Query OMC for capacity vs licence", a1t="AUTO", a1tool="query_cmdb",
         a2="Open monitoring ticket — CPU trend 7d", a2t="AUTO", a2tool="open_ticket",
         base_rul=80.2, top_feat="cpu_utilization_mean", top_imp=0.0688,
         degrade=0.06, sensor_lbl="CPU Util", sensor_nom=76.5, sensor_unit="%", sensor_dir="high"),
    dict(id="SN_KLK_13",  urgency="Monitor",  sub="rf_antenna",            sla=168,
         cl=71.8, ch=98.9, conf=0.640, gr=1.0, hal=0.0, cost=0, auto_n=1, to_n=1, hum_n=0, cov=1.00,
         doc="MAN-RF-001", subset="FD004", cycles=156,
         hyp="PA efficiency gradual decline — Kolda site sector Beta",
         fc="Power amplifier PA-3 module", mech="PA aging causing 15% efficiency drop",
         alm="RF-004 (PA efficiency) if <70%",
         a1="Schedule PA module inspection within 14d", a1t="AUTO", a1tool="open_ticket",
         a2="Monitor PA efficiency trend", a2t="AUTO", a2tool="open_ticket",
         base_rul=85.3, top_feat="rssi_std_30", top_imp=0.0601,
         degrade=0.05, sensor_lbl="PA Efficiency", sensor_nom=74.2, sensor_unit="%", sensor_dir="low"),
    dict(id="ML_SGU_24",  urgency="Monitor",  sub="power_subsystem",       sla=168,
         cl=78.2, ch=107.5, conf=0.625, gr=1.0, hal=0.0, cost=0, auto_n=2, to_n=0, hum_n=0, cov=1.00,
         doc="MAN-PWR-002", subset="FD002", cycles=125,
         hyp="Power subsystem voltage ripple increase — Ségou site",
         fc="Rectifier filtering capacitors", mech="ESR increase causing 3.2V ripple",
         alm="PWR-006 (ripple high) if >5V",
         a1="Open monitoring — voltage ripple trend", a1t="AUTO", a1tool="open_ticket",
         a2="Plan capacitor replacement if ripple >4V", a2t="AUTO", a2tool="open_ticket",
         base_rul=92.8, top_feat="voltage_rolling_mean", top_imp=0.0589,
         degrade=0.04, sensor_lbl="DC Ripple", sensor_nom=3.2, sensor_unit="V", sensor_dir="high"),
    dict(id="ML_GAO_21",  urgency="Critical", sub="thermal_management",    sla=4,
         cl=10.5, ch=17.3, conf=0.915, gr=1.0, hal=0.0, cost=830, auto_n=1, to_n=0, hum_n=2, cov=1.00,
         doc="SOP-THM-001", subset="FD003", cycles=302,
         hyp="Critical cooling failure — Gao site desert environment",
         fc="Cooling fan primary + backup failure", mech="Sand ingress causing bearing seizure",
         alm="COOL-001 + COOL-003 (shutdown risk)",
         a1="Emergency TX power reduction 70%", a1t="AUTO", a1tool="remote_command",
         a2="Critical dispatch — Gao remote site ≤4h", a2t="HUMAN", a2tool="schedule_dispatch",
         base_rul=13.9, top_feat="temp_sensor_slope", top_imp=0.0912,
         degrade=0.68, sensor_lbl="Cabinet Temp", sensor_nom=73.8, sensor_unit="°C", sensor_dir="high"),
]

# Add "rul" alias for backward compatibility
for _s in STATIONS:
    _s["rul"] = _s["base_rul"]

# Create simple nominals dict for simulation (used by data_connector.py)
STATION_NOMINALS = {}
for station in STATIONS:
    sid = station["id"]
    STATION_NOMINALS[sid] = {
        "dc_voltage_v" if "Voltage" in station["sensor_lbl"] else
        "cabinet_temp_c" if "Temp" in station["sensor_lbl"] else
        "fan_speed_rpm" if "Fan" in station["sensor_lbl"] else
        "vswr_ratio" if "VSWR" in station["sensor_lbl"] else
        "latency_ms" if "Latency" in station["sensor_lbl"] or "ESR" in station["sensor_lbl"] or "Fade" in station["sensor_lbl"] else
        "rssi_dbm" if "RSSI" in station["sensor_lbl"] else
        "cpu_util_pct" if "CPU" in station["sensor_lbl"] or "Health" in station["sensor_lbl"] else
        "battery_cap_pct" if "Battery" in station["sensor_lbl"] else
        "pa_efficiency_pct" if "PA" in station["sensor_lbl"] else
        "mem_util_pct" if "Mem" in station["sensor_lbl"] else
        "sensor_value": station["sensor_nom"],
        "sub": station["sub"],
        "degrade": station["degrade"],
        "dir": -1 if station["sensor_dir"] == "low" else 1
    }
